# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import os
import typing

import httpx
from .core.api_error import ApiError
from .core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .core.logging import LogConfig, Logger
from .environment import Trading212ClientEnvironment

if typing.TYPE_CHECKING:
    from .account.client import AccountClient, AsyncAccountClient
    from .history.client import AsyncHistoryClient, HistoryClient
    from .instruments.client import AsyncInstrumentsClient, InstrumentsClient
    from .orders.client import AsyncOrdersClient, OrdersClient
    from .pies.client import AsyncPiesClient, PiesClient
    from .positions.client import AsyncPositionsClient, PositionsClient


class Trading212Client:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : typing.Optional[str]
        The base url to use for requests from the client.

    environment : Trading212ClientEnvironment
        The environment to use for requests from the client. from .environment import Trading212ClientEnvironment



        Defaults to Trading212ClientEnvironment.DEMO



    api_key : typing.Optional[typing.Union[str, typing.Callable[[], str]]]
    api_secret : typing.Optional[typing.Union[str, typing.Callable[[], str]]]
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    max_retries : typing.Optional[int]
        The default maximum number of retries for failed requests. Defaults to 2. Per-request `max_retries` in `request_options` takes precedence over this value.

    stream_reconnection_enabled : typing.Optional[bool]
        Whether to automatically reconnect on stream disconnection for resumable streaming endpoints. Defaults to True. Per-request `stream_reconnection_enabled` in `request_options` takes precedence over this value.

    max_stream_reconnection_attempts : typing.Optional[int]
        The maximum number of reconnection attempts for resumable streaming endpoints. Defaults to no limit. Per-request `max_stream_reconnection_attempts` in `request_options` takes precedence over this value.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.Client]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    logging : typing.Optional[typing.Union[LogConfig, Logger]]
        Configure logging for the SDK. Accepts a LogConfig dict with 'level' (debug/info/warn/error), 'logger' (custom logger implementation), and 'silent' (boolean, defaults to True) fields. You can also pass a pre-configured Logger instance.

    Examples
    --------
    from t212 import Trading212Client

    client = Trading212Client(
        api_key="YOUR_API_KEY",
        api_secret="YOUR_API_SECRET",
    )
    """

    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: Trading212ClientEnvironment = Trading212ClientEnvironment.DEMO,
        api_key: typing.Optional[typing.Union[str, typing.Callable[[], str]]] = os.getenv("T212_API_KEY"),
        api_secret: typing.Optional[typing.Union[str, typing.Callable[[], str]]] = os.getenv("T212_API_SECRET"),
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        max_retries: typing.Optional[int] = None,
        stream_reconnection_enabled: typing.Optional[bool] = None,
        max_stream_reconnection_attempts: typing.Optional[int] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.Client] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
    ):
        _defaulted_timeout = timeout if timeout is not None else 60 if httpx_client is None else None
        _defaulted_max_retries = max_retries if max_retries is not None else 2
        if api_key is None:
            raise ApiError(body="The client must be instantiated be either passing in api_key or setting T212_API_KEY")
        if api_secret is None:
            raise ApiError(
                body="The client must be instantiated be either passing in api_secret or setting T212_API_SECRET"
            )
        self._client_wrapper = SyncClientWrapper(
            base_url=_get_base_url(base_url=base_url, environment=environment),
            api_key=api_key,
            api_secret=api_secret,
            headers=headers,
            httpx_client=httpx_client
            if httpx_client is not None
            else httpx.Client(timeout=_defaulted_timeout, follow_redirects=follow_redirects)
            if follow_redirects is not None
            else httpx.Client(timeout=_defaulted_timeout),
            timeout=_defaulted_timeout,
            max_retries=_defaulted_max_retries,
            stream_reconnection_enabled=stream_reconnection_enabled,
            max_stream_reconnection_attempts=max_stream_reconnection_attempts,
            logging=logging,
        )
        self._account: typing.Optional[AccountClient] = None
        self._history: typing.Optional[HistoryClient] = None
        self._instruments: typing.Optional[InstrumentsClient] = None
        self._orders: typing.Optional[OrdersClient] = None
        self._pies: typing.Optional[PiesClient] = None
        self._positions: typing.Optional[PositionsClient] = None

    @property
    def account(self):
        if self._account is None:
            from .account.client import AccountClient  # noqa: E402

            self._account = AccountClient(client_wrapper=self._client_wrapper)
        return self._account

    @property
    def history(self):
        if self._history is None:
            from .history.client import HistoryClient  # noqa: E402

            self._history = HistoryClient(client_wrapper=self._client_wrapper)
        return self._history

    @property
    def instruments(self):
        if self._instruments is None:
            from .instruments.client import InstrumentsClient  # noqa: E402

            self._instruments = InstrumentsClient(client_wrapper=self._client_wrapper)
        return self._instruments

    @property
    def orders(self):
        if self._orders is None:
            from .orders.client import OrdersClient  # noqa: E402

            self._orders = OrdersClient(client_wrapper=self._client_wrapper)
        return self._orders

    @property
    def pies(self):
        if self._pies is None:
            from .pies.client import PiesClient  # noqa: E402

            self._pies = PiesClient(client_wrapper=self._client_wrapper)
        return self._pies

    @property
    def positions(self):
        if self._positions is None:
            from .positions.client import PositionsClient  # noqa: E402

            self._positions = PositionsClient(client_wrapper=self._client_wrapper)
        return self._positions


def _make_default_async_client(
    timeout: typing.Optional[float],
    follow_redirects: typing.Optional[bool],
) -> httpx.AsyncClient:
    try:
        import httpx_aiohttp  # type: ignore[import-not-found]
    except ImportError:
        pass
    else:
        if follow_redirects is not None:
            return httpx_aiohttp.HttpxAiohttpClient(timeout=timeout, follow_redirects=follow_redirects)
        return httpx_aiohttp.HttpxAiohttpClient(timeout=timeout)

    if follow_redirects is not None:
        return httpx.AsyncClient(timeout=timeout, follow_redirects=follow_redirects)
    return httpx.AsyncClient(timeout=timeout)


class AsyncTrading212Client:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : typing.Optional[str]
        The base url to use for requests from the client.

    environment : Trading212ClientEnvironment
        The environment to use for requests from the client. from .environment import Trading212ClientEnvironment



        Defaults to Trading212ClientEnvironment.DEMO



    api_key : typing.Optional[typing.Union[str, typing.Callable[[], str]]]
    api_secret : typing.Optional[typing.Union[str, typing.Callable[[], str]]]
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    max_retries : typing.Optional[int]
        The default maximum number of retries for failed requests. Defaults to 2. Per-request `max_retries` in `request_options` takes precedence over this value.

    stream_reconnection_enabled : typing.Optional[bool]
        Whether to automatically reconnect on stream disconnection for resumable streaming endpoints. Defaults to True. Per-request `stream_reconnection_enabled` in `request_options` takes precedence over this value.

    max_stream_reconnection_attempts : typing.Optional[int]
        The maximum number of reconnection attempts for resumable streaming endpoints. Defaults to no limit. Per-request `max_stream_reconnection_attempts` in `request_options` takes precedence over this value.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.AsyncClient]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    logging : typing.Optional[typing.Union[LogConfig, Logger]]
        Configure logging for the SDK. Accepts a LogConfig dict with 'level' (debug/info/warn/error), 'logger' (custom logger implementation), and 'silent' (boolean, defaults to True) fields. You can also pass a pre-configured Logger instance.

    Examples
    --------
    from t212 import AsyncTrading212Client

    client = AsyncTrading212Client(
        api_key="YOUR_API_KEY",
        api_secret="YOUR_API_SECRET",
    )
    """

    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: Trading212ClientEnvironment = Trading212ClientEnvironment.DEMO,
        api_key: typing.Optional[typing.Union[str, typing.Callable[[], str]]] = os.getenv("T212_API_KEY"),
        api_secret: typing.Optional[typing.Union[str, typing.Callable[[], str]]] = os.getenv("T212_API_SECRET"),
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        max_retries: typing.Optional[int] = None,
        stream_reconnection_enabled: typing.Optional[bool] = None,
        max_stream_reconnection_attempts: typing.Optional[int] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.AsyncClient] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
    ):
        _defaulted_timeout = timeout if timeout is not None else 60 if httpx_client is None else None
        _defaulted_max_retries = max_retries if max_retries is not None else 2
        if api_key is None:
            raise ApiError(body="The client must be instantiated be either passing in api_key or setting T212_API_KEY")
        if api_secret is None:
            raise ApiError(
                body="The client must be instantiated be either passing in api_secret or setting T212_API_SECRET"
            )
        self._client_wrapper = AsyncClientWrapper(
            base_url=_get_base_url(base_url=base_url, environment=environment),
            api_key=api_key,
            api_secret=api_secret,
            headers=headers,
            httpx_client=httpx_client
            if httpx_client is not None
            else _make_default_async_client(timeout=_defaulted_timeout, follow_redirects=follow_redirects),
            timeout=_defaulted_timeout,
            max_retries=_defaulted_max_retries,
            stream_reconnection_enabled=stream_reconnection_enabled,
            max_stream_reconnection_attempts=max_stream_reconnection_attempts,
            logging=logging,
        )
        self._account: typing.Optional[AsyncAccountClient] = None
        self._history: typing.Optional[AsyncHistoryClient] = None
        self._instruments: typing.Optional[AsyncInstrumentsClient] = None
        self._orders: typing.Optional[AsyncOrdersClient] = None
        self._pies: typing.Optional[AsyncPiesClient] = None
        self._positions: typing.Optional[AsyncPositionsClient] = None

    @property
    def account(self):
        if self._account is None:
            from .account.client import AsyncAccountClient  # noqa: E402

            self._account = AsyncAccountClient(client_wrapper=self._client_wrapper)
        return self._account

    @property
    def history(self):
        if self._history is None:
            from .history.client import AsyncHistoryClient  # noqa: E402

            self._history = AsyncHistoryClient(client_wrapper=self._client_wrapper)
        return self._history

    @property
    def instruments(self):
        if self._instruments is None:
            from .instruments.client import AsyncInstrumentsClient  # noqa: E402

            self._instruments = AsyncInstrumentsClient(client_wrapper=self._client_wrapper)
        return self._instruments

    @property
    def orders(self):
        if self._orders is None:
            from .orders.client import AsyncOrdersClient  # noqa: E402

            self._orders = AsyncOrdersClient(client_wrapper=self._client_wrapper)
        return self._orders

    @property
    def pies(self):
        if self._pies is None:
            from .pies.client import AsyncPiesClient  # noqa: E402

            self._pies = AsyncPiesClient(client_wrapper=self._client_wrapper)
        return self._pies

    @property
    def positions(self):
        if self._positions is None:
            from .positions.client import AsyncPositionsClient  # noqa: E402

            self._positions = AsyncPositionsClient(client_wrapper=self._client_wrapper)
        return self._positions


def _get_base_url(*, base_url: typing.Optional[str] = None, environment: Trading212ClientEnvironment) -> str:
    if base_url is not None:
        return base_url
    elif environment is not None:
        return environment.value
    else:
        raise Exception("Please pass in either base_url or environment to construct the client")
