# This file was auto-generated by Fern from our API Definition.

import enum


class Trading212ClientEnvironment(enum.Enum):
    DEMO = "https://demo.trading212.com"
    LIVE = "https://live.trading212.com"
