# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.exchange import Exchange
from ..types.tradable_instrument import TradableInstrument
from .raw_client import AsyncRawInstrumentsClient, RawInstrumentsClient


class InstrumentsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawInstrumentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawInstrumentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawInstrumentsClient
        """
        return self._raw_client

    def list_exchanges(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.List[Exchange]:
        """
        Retrieves all accessible exchanges and their corresponding working schedules.
        Data is refreshed every 10 minutes.

        **Rate limit:** 1 req / 30s

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[Exchange]
            OK

        Examples
        --------
        from t212 import Trading212Client

        client = Trading212Client(
            api_key="YOUR_API_KEY",
            api_secret="YOUR_API_SECRET",
        )
        client.instruments.list_exchanges()
        """
        _response = self._raw_client.list_exchanges(request_options=request_options)
        return _response.data

    def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.List[TradableInstrument]:
        """
        Retrieves all accessible instruments.
        Data is refreshed every 10 minutes.

        **Rate limit:** 1 req / 50s

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[TradableInstrument]
            OK

        Examples
        --------
        from t212 import Trading212Client

        client = Trading212Client(
            api_key="YOUR_API_KEY",
            api_secret="YOUR_API_SECRET",
        )
        client.instruments.list()
        """
        _response = self._raw_client.list(request_options=request_options)
        return _response.data


class AsyncInstrumentsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawInstrumentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawInstrumentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawInstrumentsClient
        """
        return self._raw_client

    async def list_exchanges(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.List[Exchange]:
        """
        Retrieves all accessible exchanges and their corresponding working schedules.
        Data is refreshed every 10 minutes.

        **Rate limit:** 1 req / 30s

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[Exchange]
            OK

        Examples
        --------
        import asyncio

        from t212 import AsyncTrading212Client

        client = AsyncTrading212Client(
            api_key="YOUR_API_KEY",
            api_secret="YOUR_API_SECRET",
        )


        async def main() -> None:
            await client.instruments.list_exchanges()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_exchanges(request_options=request_options)
        return _response.data

    async def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.List[TradableInstrument]:
        """
        Retrieves all accessible instruments.
        Data is refreshed every 10 minutes.

        **Rate limit:** 1 req / 50s

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[TradableInstrument]
            OK

        Examples
        --------
        import asyncio

        from t212 import AsyncTrading212Client

        client = AsyncTrading212Client(
            api_key="YOUR_API_KEY",
            api_secret="YOUR_API_SECRET",
        )


        async def main() -> None:
            await client.instruments.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(request_options=request_options)
        return _response.data
