# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.position import Position
from .raw_client import AsyncRawPositionsClient, RawPositionsClient


class PositionsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawPositionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawPositionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPositionsClient
        """
        return self._raw_client

    def list(
        self, *, ticker: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[Position]:
        """
        Fetch all open positions for your account

        **Rate limit:** 1 req / 1s

        Parameters
        ----------
        ticker : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[Position]
            OK

        Examples
        --------
        from t212 import Trading212Client

        client = Trading212Client(
            api_key="YOUR_API_KEY",
            api_secret="YOUR_API_SECRET",
        )
        client.positions.list(
            ticker="AAPL_US_EQ",
        )
        """
        _response = self._raw_client.list(ticker=ticker, request_options=request_options)
        return _response.data


class AsyncPositionsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawPositionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawPositionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPositionsClient
        """
        return self._raw_client

    async def list(
        self, *, ticker: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[Position]:
        """
        Fetch all open positions for your account

        **Rate limit:** 1 req / 1s

        Parameters
        ----------
        ticker : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[Position]
            OK

        Examples
        --------
        import asyncio

        from t212 import AsyncTrading212Client

        client = AsyncTrading212Client(
            api_key="YOUR_API_KEY",
            api_secret="YOUR_API_SECRET",
        )


        async def main() -> None:
            await client.positions.list(
                ticker="AAPL_US_EQ",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(ticker=ticker, request_options=request_options)
        return _response.data
