# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.enqueued_report_response import EnqueuedReportResponse
from ..types.paginated_response_historical_order import PaginatedResponseHistoricalOrder
from ..types.paginated_response_history_dividend_item import PaginatedResponseHistoryDividendItem
from ..types.paginated_response_history_transaction_item import PaginatedResponseHistoryTransactionItem
from ..types.report_data_included import ReportDataIncluded
from ..types.report_response import ReportResponse
from .raw_client import AsyncRawHistoryClient, RawHistoryClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class HistoryClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawHistoryClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawHistoryClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawHistoryClient
        """
        return self._raw_client

    def list_dividends(
        self,
        *,
        cursor: typing.Optional[int] = None,
        ticker: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedResponseHistoryDividendItem:
        """


        **Rate limit:** 6 req / 1m0s

        Parameters
        ----------
        cursor : typing.Optional[int]
            Pagination cursor

        ticker : typing.Optional[str]
            Ticker filter

        limit : typing.Optional[int]
            Max items: 50

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedResponseHistoryDividendItem
            OK

        Examples
        --------
        from t212 import Trading212Client

        client = Trading212Client(
            api_key="YOUR_API_KEY",
            api_secret="YOUR_API_SECRET",
        )
        client.history.list_dividends()
        """
        _response = self._raw_client.list_dividends(
            cursor=cursor, ticker=ticker, limit=limit, request_options=request_options
        )
        return _response.data

    def list_reports(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.List[ReportResponse]:
        """
        Retrieves a list of all requested CSV reports and their current status.


        **Asynchronous Workflow:**

        1. Call `POST /history/exports` to request a report. You will receive a
        `reportId`.

        2. Periodically call this endpoint (`GET /history/exports`) to check the
        `status` of the report corresponding to your `reportId`.

        3. Once the status is `Finished`, the `downloadLink` field will contain
        a URL to download the CSV file.

        **Rate limit:** 1 req / 1m0s

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[ReportResponse]
            OK

        Examples
        --------
        from t212 import Trading212Client

        client = Trading212Client(
            api_key="YOUR_API_KEY",
            api_secret="YOUR_API_SECRET",
        )
        client.history.list_reports()
        """
        _response = self._raw_client.list_reports(request_options=request_options)
        return _response.data

    def request_report(
        self,
        *,
        data_included: typing.Optional[ReportDataIncluded] = OMIT,
        time_from: typing.Optional[dt.datetime] = OMIT,
        time_to: typing.Optional[dt.datetime] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EnqueuedReportResponse:
        """
        Initiates the generation of a CSV report containing historical account
        data. This is an asynchronous operation. The response will include a
        `reportId` which you can use to track the status of the generation
        process using the `GET /history/exports` endpoint.

        **Rate limit:** 1 req / 30s

        Parameters
        ----------
        data_included : typing.Optional[ReportDataIncluded]

        time_from : typing.Optional[dt.datetime]

        time_to : typing.Optional[dt.datetime]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EnqueuedReportResponse
            OK

        Examples
        --------
        from t212 import Trading212Client

        client = Trading212Client(
            api_key="YOUR_API_KEY",
            api_secret="YOUR_API_SECRET",
        )
        client.history.request_report()
        """
        _response = self._raw_client.request_report(
            data_included=data_included, time_from=time_from, time_to=time_to, request_options=request_options
        )
        return _response.data

    def list_orders(
        self,
        *,
        cursor: typing.Optional[int] = None,
        ticker: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedResponseHistoricalOrder:
        """


        **Rate limit:** 6 req / 1m0s

        Parameters
        ----------
        cursor : typing.Optional[int]
            Pagination cursor

        ticker : typing.Optional[str]
            Ticker filter

        limit : typing.Optional[int]
            Max items: 50

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedResponseHistoricalOrder
            OK

        Examples
        --------
        from t212 import Trading212Client

        client = Trading212Client(
            api_key="YOUR_API_KEY",
            api_secret="YOUR_API_SECRET",
        )
        client.history.list_orders()
        """
        _response = self._raw_client.list_orders(
            cursor=cursor, ticker=ticker, limit=limit, request_options=request_options
        )
        return _response.data

    def list_transactions(
        self,
        *,
        cursor: typing.Optional[str] = None,
        time: typing.Optional[dt.datetime] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedResponseHistoryTransactionItem:
        """
        Fetch superficial information about movements to and from your account

        **Rate limit:** 6 req / 1m0s

        Parameters
        ----------
        cursor : typing.Optional[str]
            Pagination cursor

        time : typing.Optional[dt.datetime]
            Retrieve transactions starting from the specified time

        limit : typing.Optional[int]
            Max items: 50

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedResponseHistoryTransactionItem
            OK

        Examples
        --------
        from t212 import Trading212Client

        client = Trading212Client(
            api_key="YOUR_API_KEY",
            api_secret="YOUR_API_SECRET",
        )
        client.history.list_transactions()
        """
        _response = self._raw_client.list_transactions(
            cursor=cursor, time=time, limit=limit, request_options=request_options
        )
        return _response.data


class AsyncHistoryClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawHistoryClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawHistoryClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawHistoryClient
        """
        return self._raw_client

    async def list_dividends(
        self,
        *,
        cursor: typing.Optional[int] = None,
        ticker: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedResponseHistoryDividendItem:
        """


        **Rate limit:** 6 req / 1m0s

        Parameters
        ----------
        cursor : typing.Optional[int]
            Pagination cursor

        ticker : typing.Optional[str]
            Ticker filter

        limit : typing.Optional[int]
            Max items: 50

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedResponseHistoryDividendItem
            OK

        Examples
        --------
        import asyncio

        from t212 import AsyncTrading212Client

        client = AsyncTrading212Client(
            api_key="YOUR_API_KEY",
            api_secret="YOUR_API_SECRET",
        )


        async def main() -> None:
            await client.history.list_dividends()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_dividends(
            cursor=cursor, ticker=ticker, limit=limit, request_options=request_options
        )
        return _response.data

    async def list_reports(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[ReportResponse]:
        """
        Retrieves a list of all requested CSV reports and their current status.


        **Asynchronous Workflow:**

        1. Call `POST /history/exports` to request a report. You will receive a
        `reportId`.

        2. Periodically call this endpoint (`GET /history/exports`) to check the
        `status` of the report corresponding to your `reportId`.

        3. Once the status is `Finished`, the `downloadLink` field will contain
        a URL to download the CSV file.

        **Rate limit:** 1 req / 1m0s

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[ReportResponse]
            OK

        Examples
        --------
        import asyncio

        from t212 import AsyncTrading212Client

        client = AsyncTrading212Client(
            api_key="YOUR_API_KEY",
            api_secret="YOUR_API_SECRET",
        )


        async def main() -> None:
            await client.history.list_reports()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_reports(request_options=request_options)
        return _response.data

    async def request_report(
        self,
        *,
        data_included: typing.Optional[ReportDataIncluded] = OMIT,
        time_from: typing.Optional[dt.datetime] = OMIT,
        time_to: typing.Optional[dt.datetime] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EnqueuedReportResponse:
        """
        Initiates the generation of a CSV report containing historical account
        data. This is an asynchronous operation. The response will include a
        `reportId` which you can use to track the status of the generation
        process using the `GET /history/exports` endpoint.

        **Rate limit:** 1 req / 30s

        Parameters
        ----------
        data_included : typing.Optional[ReportDataIncluded]

        time_from : typing.Optional[dt.datetime]

        time_to : typing.Optional[dt.datetime]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EnqueuedReportResponse
            OK

        Examples
        --------
        import asyncio

        from t212 import AsyncTrading212Client

        client = AsyncTrading212Client(
            api_key="YOUR_API_KEY",
            api_secret="YOUR_API_SECRET",
        )


        async def main() -> None:
            await client.history.request_report()


        asyncio.run(main())
        """
        _response = await self._raw_client.request_report(
            data_included=data_included, time_from=time_from, time_to=time_to, request_options=request_options
        )
        return _response.data

    async def list_orders(
        self,
        *,
        cursor: typing.Optional[int] = None,
        ticker: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedResponseHistoricalOrder:
        """


        **Rate limit:** 6 req / 1m0s

        Parameters
        ----------
        cursor : typing.Optional[int]
            Pagination cursor

        ticker : typing.Optional[str]
            Ticker filter

        limit : typing.Optional[int]
            Max items: 50

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedResponseHistoricalOrder
            OK

        Examples
        --------
        import asyncio

        from t212 import AsyncTrading212Client

        client = AsyncTrading212Client(
            api_key="YOUR_API_KEY",
            api_secret="YOUR_API_SECRET",
        )


        async def main() -> None:
            await client.history.list_orders()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_orders(
            cursor=cursor, ticker=ticker, limit=limit, request_options=request_options
        )
        return _response.data

    async def list_transactions(
        self,
        *,
        cursor: typing.Optional[str] = None,
        time: typing.Optional[dt.datetime] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedResponseHistoryTransactionItem:
        """
        Fetch superficial information about movements to and from your account

        **Rate limit:** 6 req / 1m0s

        Parameters
        ----------
        cursor : typing.Optional[str]
            Pagination cursor

        time : typing.Optional[dt.datetime]
            Retrieve transactions starting from the specified time

        limit : typing.Optional[int]
            Max items: 50

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedResponseHistoryTransactionItem
            OK

        Examples
        --------
        import asyncio

        from t212 import AsyncTrading212Client

        client = AsyncTrading212Client(
            api_key="YOUR_API_KEY",
            api_secret="YOUR_API_SECRET",
        )


        async def main() -> None:
            await client.history.list_transactions()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_transactions(
            cursor=cursor, time=time, limit=limit, request_options=request_options
        )
        return _response.data
