// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: 1000000
 *     }
 */
export interface DuplicateBucketRequest {
    id: number;
    icon?: string;
    name?: string;
}
