// This file was auto-generated by Fern from our API Definition.

import type * as Trading212 from "../../../../index.js";

/**
 * @example
 *     {
 *         id: 1000000,
 *         body: {}
 *     }
 */
export interface UpdatePiesRequest {
    id: number;
    body: Trading212.PieRequest;
}
