# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .account_bucket_detailed_response import AccountBucketDetailedResponse
    from .account_bucket_detailed_response_dividend_cash_action import AccountBucketDetailedResponseDividendCashAction
    from .account_bucket_instrument_result import AccountBucketInstrumentResult
    from .account_bucket_instruments_detailed_response import AccountBucketInstrumentsDetailedResponse
    from .account_bucket_result_response import AccountBucketResultResponse
    from .account_bucket_result_response_status import AccountBucketResultResponseStatus
    from .account_summary import AccountSummary
    from .cash import Cash
    from .dividend_details import DividendDetails
    from .enqueued_report_response import EnqueuedReportResponse
    from .exchange import Exchange
    from .fill import Fill
    from .fill_trading_method import FillTradingMethod
    from .fill_type import FillType
    from .fill_wallet_impact import FillWalletImpact
    from .historical_order import HistoricalOrder
    from .history_dividend_item import HistoryDividendItem
    from .history_dividend_item_type import HistoryDividendItemType
    from .history_transaction_item import HistoryTransactionItem
    from .history_transaction_item_type import HistoryTransactionItemType
    from .instrument import Instrument
    from .instrument_issue import InstrumentIssue
    from .instrument_issue_name import InstrumentIssueName
    from .instrument_issue_severity import InstrumentIssueSeverity
    from .investment_result import InvestmentResult
    from .investments import Investments
    from .order import Order
    from .order_initiated_from import OrderInitiatedFrom
    from .order_side import OrderSide
    from .order_status import OrderStatus
    from .order_strategy import OrderStrategy
    from .order_type import OrderType
    from .paginated_response_historical_order import PaginatedResponseHistoricalOrder
    from .paginated_response_history_dividend_item import PaginatedResponseHistoryDividendItem
    from .paginated_response_history_transaction_item import PaginatedResponseHistoryTransactionItem
    from .pie_request import PieRequest
    from .pie_request_dividend_cash_action import PieRequestDividendCashAction
    from .position import Position
    from .position_wallet_impact import PositionWalletImpact
    from .report_data_included import ReportDataIncluded
    from .report_response import ReportResponse
    from .report_response_status import ReportResponseStatus
    from .tax import Tax
    from .tax_name import TaxName
    from .time_event import TimeEvent
    from .time_event_type import TimeEventType
    from .time_validity import TimeValidity
    from .tradable_instrument import TradableInstrument
    from .tradable_instrument_type import TradableInstrumentType
    from .working_schedule import WorkingSchedule
_dynamic_imports: typing.Dict[str, str] = {
    "AccountBucketDetailedResponse": ".account_bucket_detailed_response",
    "AccountBucketDetailedResponseDividendCashAction": ".account_bucket_detailed_response_dividend_cash_action",
    "AccountBucketInstrumentResult": ".account_bucket_instrument_result",
    "AccountBucketInstrumentsDetailedResponse": ".account_bucket_instruments_detailed_response",
    "AccountBucketResultResponse": ".account_bucket_result_response",
    "AccountBucketResultResponseStatus": ".account_bucket_result_response_status",
    "AccountSummary": ".account_summary",
    "Cash": ".cash",
    "DividendDetails": ".dividend_details",
    "EnqueuedReportResponse": ".enqueued_report_response",
    "Exchange": ".exchange",
    "Fill": ".fill",
    "FillTradingMethod": ".fill_trading_method",
    "FillType": ".fill_type",
    "FillWalletImpact": ".fill_wallet_impact",
    "HistoricalOrder": ".historical_order",
    "HistoryDividendItem": ".history_dividend_item",
    "HistoryDividendItemType": ".history_dividend_item_type",
    "HistoryTransactionItem": ".history_transaction_item",
    "HistoryTransactionItemType": ".history_transaction_item_type",
    "Instrument": ".instrument",
    "InstrumentIssue": ".instrument_issue",
    "InstrumentIssueName": ".instrument_issue_name",
    "InstrumentIssueSeverity": ".instrument_issue_severity",
    "InvestmentResult": ".investment_result",
    "Investments": ".investments",
    "Order": ".order",
    "OrderInitiatedFrom": ".order_initiated_from",
    "OrderSide": ".order_side",
    "OrderStatus": ".order_status",
    "OrderStrategy": ".order_strategy",
    "OrderType": ".order_type",
    "PaginatedResponseHistoricalOrder": ".paginated_response_historical_order",
    "PaginatedResponseHistoryDividendItem": ".paginated_response_history_dividend_item",
    "PaginatedResponseHistoryTransactionItem": ".paginated_response_history_transaction_item",
    "PieRequest": ".pie_request",
    "PieRequestDividendCashAction": ".pie_request_dividend_cash_action",
    "Position": ".position",
    "PositionWalletImpact": ".position_wallet_impact",
    "ReportDataIncluded": ".report_data_included",
    "ReportResponse": ".report_response",
    "ReportResponseStatus": ".report_response_status",
    "Tax": ".tax",
    "TaxName": ".tax_name",
    "TimeEvent": ".time_event",
    "TimeEventType": ".time_event_type",
    "TimeValidity": ".time_validity",
    "TradableInstrument": ".tradable_instrument",
    "TradableInstrumentType": ".tradable_instrument_type",
    "WorkingSchedule": ".working_schedule",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AccountBucketDetailedResponse",
    "AccountBucketDetailedResponseDividendCashAction",
    "AccountBucketInstrumentResult",
    "AccountBucketInstrumentsDetailedResponse",
    "AccountBucketResultResponse",
    "AccountBucketResultResponseStatus",
    "AccountSummary",
    "Cash",
    "DividendDetails",
    "EnqueuedReportResponse",
    "Exchange",
    "Fill",
    "FillTradingMethod",
    "FillType",
    "FillWalletImpact",
    "HistoricalOrder",
    "HistoryDividendItem",
    "HistoryDividendItemType",
    "HistoryTransactionItem",
    "HistoryTransactionItemType",
    "Instrument",
    "InstrumentIssue",
    "InstrumentIssueName",
    "InstrumentIssueSeverity",
    "InvestmentResult",
    "Investments",
    "Order",
    "OrderInitiatedFrom",
    "OrderSide",
    "OrderStatus",
    "OrderStrategy",
    "OrderType",
    "PaginatedResponseHistoricalOrder",
    "PaginatedResponseHistoryDividendItem",
    "PaginatedResponseHistoryTransactionItem",
    "PieRequest",
    "PieRequestDividendCashAction",
    "Position",
    "PositionWalletImpact",
    "ReportDataIncluded",
    "ReportResponse",
    "ReportResponseStatus",
    "Tax",
    "TaxName",
    "TimeEvent",
    "TimeEventType",
    "TimeValidity",
    "TradableInstrument",
    "TradableInstrumentType",
    "WorkingSchedule",
]
