# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .cash import Cash
from .investments import Investments


class AccountSummary(UniversalBaseModel):
    cash: typing.Optional[Cash] = None
    currency: typing.Optional[str] = pydantic.Field(default=None)
    """
    Primary account currency in ISO 4217 format.
    """

    id: typing.Optional[int] = pydantic.Field(default=None)
    """
    Primary trading account number. This is the same account ID you would see in the Trading 212 web or mobile application.
    """

    investments: typing.Optional[Investments] = None
    total_value: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="totalValue"),
        pydantic.Field(alias="totalValue", description="Investments value in your account's primary currency."),
    ] = None
    """
    Investments value in your account's primary currency.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
