# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .account_bucket_detailed_response import AccountBucketDetailedResponse
from .account_bucket_instrument_result import AccountBucketInstrumentResult


class AccountBucketInstrumentsDetailedResponse(UniversalBaseModel):
    instruments: typing.Optional[typing.List[AccountBucketInstrumentResult]] = None
    settings: typing.Optional[AccountBucketDetailedResponse] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
