# This file was auto-generated by Fern from our API Definition.

import typing

AccountBucketDetailedResponseDividendCashAction = typing.Union[
    typing.Literal["REINVEST", "TO_ACCOUNT_CASH"], typing.Any
]
