# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .account_bucket_detailed_response_dividend_cash_action import AccountBucketDetailedResponseDividendCashAction


class AccountBucketDetailedResponse(UniversalBaseModel):
    creation_date: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="creationDate"), pydantic.Field(alias="creationDate")
    ] = None
    dividend_cash_action: typing_extensions.Annotated[
        typing.Optional[AccountBucketDetailedResponseDividendCashAction],
        FieldMetadata(alias="dividendCashAction"),
        pydantic.Field(alias="dividendCashAction"),
    ] = None
    end_date: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="endDate"), pydantic.Field(alias="endDate")
    ] = None
    goal: typing.Optional[float] = None
    icon: typing.Optional[str] = None
    id: typing.Optional[int] = None
    initial_investment: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="initialInvestment"), pydantic.Field(alias="initialInvestment")
    ] = None
    instrument_shares: typing_extensions.Annotated[
        typing.Optional[typing.Dict[str, float]],
        FieldMetadata(alias="instrumentShares"),
        pydantic.Field(alias="instrumentShares"),
    ] = None
    name: typing.Optional[str] = None
    public_url: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="publicUrl"), pydantic.Field(alias="publicUrl")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
