# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class Cash(UniversalBaseModel):
    available_to_trade: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="availableToTrade"),
        pydantic.Field(alias="availableToTrade", description="Funds available for investing."),
    ] = None
    """
    Funds available for investing.
    """

    in_pies: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="inPies"),
        pydantic.Field(
            alias="inPies", description="It’s the sum of the cash inside of all pies that is not yet invested."
        ),
    ] = None
    """
    It’s the sum of the cash inside of all pies that is not yet invested.
    """

    reserved_for_orders: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="reservedForOrders"),
        pydantic.Field(
            alias="reservedForOrders",
            description="The amount of cash reserved for pending orders. This cash is not available for placing new trades.",
        ),
    ] = None
    """
    The amount of cash reserved for pending orders. This cash is not available for placing new trades.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
