# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .tax import Tax


class FillWalletImpact(UniversalBaseModel):
    currency: typing.Optional[str] = None
    fx_rate: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="fxRate"), pydantic.Field(alias="fxRate")
    ] = None
    net_value: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="netValue"), pydantic.Field(alias="netValue")
    ] = None
    realised_profit_loss: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="realisedProfitLoss"), pydantic.Field(alias="realisedProfitLoss")
    ] = None
    taxes: typing.Optional[typing.List[Tax]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
