# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .fill_trading_method import FillTradingMethod
from .fill_type import FillType
from .fill_wallet_impact import FillWalletImpact


class Fill(UniversalBaseModel):
    filled_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="filledAt"), pydantic.Field(alias="filledAt")
    ] = None
    id: typing.Optional[int] = None
    price: typing.Optional[float] = None
    quantity: typing.Optional[float] = None
    trading_method: typing_extensions.Annotated[
        typing.Optional[FillTradingMethod], FieldMetadata(alias="tradingMethod"), pydantic.Field(alias="tradingMethod")
    ] = None
    type: typing.Optional[FillType] = None
    wallet_impact: typing_extensions.Annotated[
        typing.Optional[FillWalletImpact], FieldMetadata(alias="walletImpact"), pydantic.Field(alias="walletImpact")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
