# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .history_transaction_item_type import HistoryTransactionItemType


class HistoryTransactionItem(UniversalBaseModel):
    amount: typing.Optional[float] = pydantic.Field(default=None)
    """
    Amount in the currency of the transaction
    """

    currency: typing.Optional[str] = pydantic.Field(default=None)
    """
    Currency of the transaction
    """

    date_time: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="dateTime"), pydantic.Field(alias="dateTime")
    ] = None
    reference: typing.Optional[str] = pydantic.Field(default=None)
    """
    ID
    """

    type: typing.Optional[HistoryTransactionItemType] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
