# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .history_dividend_item_type import HistoryDividendItemType
from .instrument import Instrument


class HistoryDividendItem(UniversalBaseModel):
    amount: typing.Optional[float] = pydantic.Field(default=None)
    """
    In account's primary currency.
    """

    amount_in_euro: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="amountInEuro"), pydantic.Field(alias="amountInEuro")
    ] = None
    currency: typing.Optional[str] = pydantic.Field(default=None)
    """
    The account's primary currency.
    """

    gross_amount_per_share: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="grossAmountPerShare"),
        pydantic.Field(alias="grossAmountPerShare", description="In instrument currency"),
    ] = None
    """
    In instrument currency
    """

    instrument: typing.Optional[Instrument] = None
    paid_on: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="paidOn"), pydantic.Field(alias="paidOn")
    ] = None
    quantity: typing.Optional[float] = None
    reference: typing.Optional[str] = None
    ticker: typing.Optional[str] = None
    ticker_currency: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="tickerCurrency"), pydantic.Field(alias="tickerCurrency")
    ] = None
    type: typing.Optional[HistoryDividendItemType] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
