# This file was auto-generated by Fern from our API Definition.

import typing

HistoryTransactionItemType = typing.Union[
    typing.Literal["WITHDRAW", "DEPOSIT", "FEE", "TRANSFER", "INTEREST_ON_FREE_CASH", "LENDING_INTEREST"], typing.Any
]
