# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .instrument_issue_name import InstrumentIssueName
from .instrument_issue_severity import InstrumentIssueSeverity


class InstrumentIssue(UniversalBaseModel):
    name: typing.Optional[InstrumentIssueName] = None
    severity: typing.Optional[InstrumentIssueSeverity] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
