# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class Instrument(UniversalBaseModel):
    """
    Instrument information as given by /instruments endpoint.
    """

    currency: typing.Optional[str] = pydantic.Field(default=None)
    """
    Instrument currency in ISO 4217 format.
    """

    isin: typing.Optional[str] = pydantic.Field(default=None)
    """
    ISIN of the instrument.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Name of the instrument.
    """

    ticker: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unique instrument identifier.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
