# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class Investments(UniversalBaseModel):
    current_value: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="currentValue"),
        pydantic.Field(alias="currentValue", description="Current value of all the investments."),
    ] = None
    """
    Current value of all the investments.
    """

    realized_profit_loss: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="realizedProfitLoss"),
        pydantic.Field(
            alias="realizedProfitLoss", description="The all-time realised profit loss from all of the trades executed."
        ),
    ] = None
    """
    The all-time realised profit loss from all of the trades executed.
    """

    total_cost: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="totalCost"),
        pydantic.Field(
            alias="totalCost",
            description="The cost basis of your current investments. The total amount of funds you've invested in the shares you currently own.",
        ),
    ] = None
    """
    The cost basis of your current investments. The total amount of funds you've invested in the shares you currently own.
    """

    unrealized_profit_loss: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="unrealizedProfitLoss"),
        pydantic.Field(
            alias="unrealizedProfitLoss",
            description="The potential profit/loss of your current investments, showing how much you could gain or lose if you were to sell them now.",
        ),
    ] = None
    """
    The potential profit/loss of your current investments, showing how much you could gain or lose if you were to sell them now.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
