# This file was auto-generated by Fern from our API Definition.

import typing

OrderInitiatedFrom = typing.Union[
    typing.Literal["API", "IOS", "ANDROID", "WEB", "SYSTEM", "AUTOINVEST", "INSTRUMENT_AUTOINVEST"], typing.Any
]
