# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .instrument import Instrument
from .order_initiated_from import OrderInitiatedFrom
from .order_side import OrderSide
from .order_status import OrderStatus
from .order_strategy import OrderStrategy
from .order_type import OrderType
from .time_validity import TimeValidity


class Order(UniversalBaseModel):
    created_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="createdAt"),
        pydantic.Field(alias="createdAt", description="The ISO 8601 formatted date of when the order was created."),
    ] = None
    """
    The ISO 8601 formatted date of when the order was created.
    """

    currency: typing.Optional[str] = pydantic.Field(default=None)
    """
    The currency used for the order in ISO 4217 format.
    """

    extended_hours: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="extendedHours"),
        pydantic.Field(
            alias="extendedHours",
            description="If true, the order is eligible for execution outside regular trading hours.",
        ),
    ] = None
    """
    If true, the order is eligible for execution outside regular trading hours.
    """

    filled_quantity: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="filledQuantity"),
        pydantic.Field(
            alias="filledQuantity",
            description="The number of shares that have been successfully executed. Applicable to quantity orders.",
        ),
    ] = None
    """
    The number of shares that have been successfully executed. Applicable to quantity orders.
    """

    filled_value: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="filledValue"),
        pydantic.Field(
            alias="filledValue",
            description="The total monetary value of the executed portion of the order. Applicable to orders placed by value.Note: Placing orders by value is not currently supported via the API but can be done through other Trading 212 platforms.",
        ),
    ] = None
    """
    The total monetary value of the executed portion of the order. Applicable to orders placed by value.Note: Placing orders by value is not currently supported via the API but can be done through other Trading 212 platforms.
    """

    id: typing.Optional[int] = pydantic.Field(default=None)
    """
    A unique, system-generated identifier for the order.
    """

    initiated_from: typing_extensions.Annotated[
        typing.Optional[OrderInitiatedFrom],
        FieldMetadata(alias="initiatedFrom"),
        pydantic.Field(alias="initiatedFrom", description="How the order was initiated."),
    ] = None
    """
    How the order was initiated.
    """

    instrument: typing.Optional[Instrument] = None
    limit_price: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="limitPrice"),
        pydantic.Field(alias="limitPrice", description="Applicable to LIMIT and STOP_LIMIT orders."),
    ] = None
    """
    Applicable to LIMIT and STOP_LIMIT orders.
    """

    quantity: typing.Optional[float] = pydantic.Field(default=None)
    """
    The total number of shares requested. Applicable to quantity orders.
    """

    side: typing.Optional[OrderSide] = pydantic.Field(default=None)
    """
    Indicates whether the order is BUY or SELL.
    """

    status: typing.Optional[OrderStatus] = pydantic.Field(default=None)
    """
    The current state of the order in its lifecycle.
    """

    stop_price: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="stopPrice"),
        pydantic.Field(alias="stopPrice", description="Applicable to STOP and STOP_LIMIT orders."),
    ] = None
    """
    Applicable to STOP and STOP_LIMIT orders.
    """

    strategy: typing.Optional[OrderStrategy] = pydantic.Field(default=None)
    """
    The strategy used to place the order, either by QUANTITY or VALUE. The API currently only supports placing orders by QUANTITY.
    """

    ticker: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unique instrument identifier. Get from the /instruments endpoint
    """

    time_in_force: typing_extensions.Annotated[
        typing.Optional[TimeValidity], FieldMetadata(alias="timeInForce"), pydantic.Field(alias="timeInForce")
    ] = None
    type: typing.Optional[OrderType] = None
    value: typing.Optional[float] = pydantic.Field(default=None)
    """
    The total monetary value of the order. Applicable to value orders.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
