# This file was auto-generated by Fern from our API Definition.

import typing

OrderStatus = typing.Union[
    typing.Literal[
        "LOCAL",
        "UNCONFIRMED",
        "CONFIRMED",
        "NEW",
        "CANCELLING",
        "CANCELLED",
        "PARTIALLY_FILLED",
        "FILLED",
        "REJECTED",
        "REPLACING",
        "REPLACED",
    ],
    typing.Any,
]
