# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .history_transaction_item import HistoryTransactionItem


class PaginatedResponseHistoryTransactionItem(UniversalBaseModel):
    items: typing.Optional[typing.List[HistoryTransactionItem]] = None
    next_page_path: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="nextPagePath"), pydantic.Field(alias="nextPagePath")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
