# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .pie_request_dividend_cash_action import PieRequestDividendCashAction


class PieRequest(UniversalBaseModel):
    dividend_cash_action: typing_extensions.Annotated[
        typing.Optional[PieRequestDividendCashAction],
        FieldMetadata(alias="dividendCashAction"),
        pydantic.Field(alias="dividendCashAction"),
    ] = None
    end_date: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="endDate"), pydantic.Field(alias="endDate")
    ] = None
    goal: typing.Optional[float] = pydantic.Field(default=None)
    """
    Total desired value of the pie in account currency
    """

    icon: typing.Optional[str] = None
    instrument_shares: typing_extensions.Annotated[
        typing.Optional[typing.Dict[str, float]],
        FieldMetadata(alias="instrumentShares"),
        pydantic.Field(alias="instrumentShares"),
    ] = None
    name: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
