# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class PositionWalletImpact(UniversalBaseModel):
    currency: typing.Optional[str] = pydantic.Field(default=None)
    """
    The currency code used to represent all the wallet impact information.
    """

    current_value: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="currentValue"),
        pydantic.Field(alias="currentValue", description="The current market value of the position."),
    ] = None
    """
    The current market value of the position.
    """

    fx_impact: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="fxImpact"),
        pydantic.Field(
            alias="fxImpact",
            description="The positive or negative impact on the position's value due to currency rate changes. Only applies to positions with instrument currency that differs from the accounts.",
        ),
    ] = None
    """
    The positive or negative impact on the position's value due to currency rate changes. Only applies to positions with instrument currency that differs from the accounts.
    """

    total_cost: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="totalCost"),
        pydantic.Field(alias="totalCost", description="The total cost paid for the position."),
    ] = None
    """
    The total cost paid for the position.
    """

    unrealized_profit_loss: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="unrealizedProfitLoss"),
        pydantic.Field(
            alias="unrealizedProfitLoss",
            description="The unrealized profit & loss for the position. Calculated as currentValue - totalCost.",
        ),
    ] = None
    """
    The unrealized profit & loss for the position. Calculated as currentValue - totalCost.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
