# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .instrument import Instrument
from .position_wallet_impact import PositionWalletImpact


class Position(UniversalBaseModel):
    average_price_paid: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="averagePricePaid"),
        pydantic.Field(alias="averagePricePaid", description="Average price paid, in instrument currency, per share."),
    ] = None
    """
    Average price paid, in instrument currency, per share.
    """

    created_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="createdAt"),
        pydantic.Field(alias="createdAt", description="The ISO 8601 formatted date of when the position was opened."),
    ] = None
    """
    The ISO 8601 formatted date of when the position was opened.
    """

    current_price: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="currentPrice"),
        pydantic.Field(alias="currentPrice", description="Current price, in instrument currency, of a single share."),
    ] = None
    """
    Current price, in instrument currency, of a single share.
    """

    instrument: typing.Optional[Instrument] = None
    quantity: typing.Optional[float] = pydantic.Field(default=None)
    """
    Total quantity of shares owned.
    """

    quantity_available_for_trading: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="quantityAvailableForTrading"),
        pydantic.Field(alias="quantityAvailableForTrading", description="Quantity of shares available for trading."),
    ] = None
    """
    Quantity of shares available for trading.
    """

    quantity_in_pies: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="quantityInPies"),
        pydantic.Field(alias="quantityInPies", description="Quantity of shares currently used in pie."),
    ] = None
    """
    Quantity of shares currently used in pie.
    """

    wallet_impact: typing_extensions.Annotated[
        typing.Optional[PositionWalletImpact],
        FieldMetadata(alias="walletImpact"),
        pydantic.Field(
            alias="walletImpact", description="Collects the financial impact of the position on the user's wallet."
        ),
    ] = None
    """
    Collects the financial impact of the position on the user's wallet.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
