# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .report_data_included import ReportDataIncluded
from .report_response_status import ReportResponseStatus


class ReportResponse(UniversalBaseModel):
    data_included: typing_extensions.Annotated[
        typing.Optional[ReportDataIncluded], FieldMetadata(alias="dataIncluded"), pydantic.Field(alias="dataIncluded")
    ] = None
    download_link: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="downloadLink"), pydantic.Field(alias="downloadLink")
    ] = None
    report_id: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="reportId"), pydantic.Field(alias="reportId")
    ] = None
    status: typing.Optional[ReportResponseStatus] = None
    time_from: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="timeFrom"), pydantic.Field(alias="timeFrom")
    ] = None
    time_to: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="timeTo"), pydantic.Field(alias="timeTo")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
