# This file was auto-generated by Fern from our API Definition.

import typing

ReportResponseStatus = typing.Union[
    typing.Literal["Queued", "Processing", "Running", "Canceled", "Failed", "Finished"], typing.Any
]
