# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class ReportDataIncluded(UniversalBaseModel):
    include_dividends: typing_extensions.Annotated[
        typing.Optional[bool], FieldMetadata(alias="includeDividends"), pydantic.Field(alias="includeDividends")
    ] = None
    include_interest: typing_extensions.Annotated[
        typing.Optional[bool], FieldMetadata(alias="includeInterest"), pydantic.Field(alias="includeInterest")
    ] = None
    include_orders: typing_extensions.Annotated[
        typing.Optional[bool], FieldMetadata(alias="includeOrders"), pydantic.Field(alias="includeOrders")
    ] = None
    include_transactions: typing_extensions.Annotated[
        typing.Optional[bool], FieldMetadata(alias="includeTransactions"), pydantic.Field(alias="includeTransactions")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
