# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .tax_name import TaxName


class Tax(UniversalBaseModel):
    charged_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="chargedAt"), pydantic.Field(alias="chargedAt")
    ] = None
    currency: typing.Optional[str] = None
    name: typing.Optional[TaxName] = None
    quantity: typing.Optional[float] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
