# This file was auto-generated by Fern from our API Definition.

import typing

TaxName = typing.Union[
    typing.Literal[
        "COMMISSION_TURNOVER",
        "CURRENCY_CONVERSION_FEE",
        "FINRA_FEE",
        "FRENCH_TRANSACTION_TAX",
        "PTM_LEVY",
        "STAMP_DUTY",
        "STAMP_DUTY_RESERVE_TAX",
        "TRANSACTION_FEE",
    ],
    typing.Any,
]
