# This file was auto-generated by Fern from our API Definition.

import typing

TimeEventType = typing.Union[
    typing.Literal[
        "OPEN",
        "CLOSE",
        "BREAK_START",
        "BREAK_END",
        "PRE_MARKET_OPEN",
        "AFTER_HOURS_OPEN",
        "AFTER_HOURS_CLOSE",
        "OVERNIGHT_OPEN",
    ],
    typing.Any,
]
