# This file was auto-generated by Fern from our API Definition.

import typing

TradableInstrumentType = typing.Union[
    typing.Literal[
        "CRYPTOCURRENCY", "ETF", "FOREX", "FUTURES", "INDEX", "STOCK", "WARRANT", "CRYPTO", "CVR", "CORPACT"
    ],
    typing.Any,
]
