# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .tradable_instrument_type import TradableInstrumentType


class TradableInstrument(UniversalBaseModel):
    added_on: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="addedOn"),
        pydantic.Field(alias="addedOn", description="On the platform since"),
    ] = None
    """
    On the platform since
    """

    currency_code: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="currencyCode"),
        pydantic.Field(alias="currencyCode", description="ISO 4217"),
    ] = None
    """
    ISO 4217
    """

    extended_hours: typing_extensions.Annotated[
        typing.Optional[bool], FieldMetadata(alias="extendedHours"), pydantic.Field(alias="extendedHours")
    ] = None
    isin: typing.Optional[str] = None
    max_open_quantity: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="maxOpenQuantity"), pydantic.Field(alias="maxOpenQuantity")
    ] = None
    name: typing.Optional[str] = None
    short_name: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="shortName"), pydantic.Field(alias="shortName")
    ] = None
    ticker: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unique identifier
    """

    type: typing.Optional[TradableInstrumentType] = None
    working_schedule_id: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="workingScheduleId"),
        pydantic.Field(alias="workingScheduleId", description="Get items in the /exchanges endpoint"),
    ] = None
    """
    Get items in the /exchanges endpoint
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
