// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListOrdersHistoryRequest {
    /** Pagination cursor */
    cursor?: number;
    /** Ticker filter */
    ticker?: string;
    /** Max items: 50 */
    limit?: number;
}
