// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListTransactionsHistoryRequest {
    /** Pagination cursor */
    cursor?: string;
    /** Retrieve transactions starting from the specified time */
    time?: string;
    /** Max items: 50 */
    limit?: number;
}
