// This file was auto-generated by Fern from our API Definition.

import type * as Trading212 from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface PublicReportRequest {
    dataIncluded?: Trading212.ReportDataIncluded;
    timeFrom?: string;
    timeTo?: string;
}
