// This file was auto-generated by Fern from our API Definition.

import { AccountClient } from "./api/resources/account/client/Client.js";
import { HistoryClient } from "./api/resources/history/client/Client.js";
import { InstrumentsClient } from "./api/resources/instruments/client/Client.js";
import { OrdersClient } from "./api/resources/orders/client/Client.js";
import { PiesClient } from "./api/resources/pies/client/Client.js";
import { PositionsClient } from "./api/resources/positions/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";
import * as core from "./core/index.js";

export declare namespace Trading212Client {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class Trading212Client {
    protected readonly _options: NormalizedClientOptionsWithAuth<Trading212Client.Options>;
    protected _account: AccountClient | undefined;
    protected _history: HistoryClient | undefined;
    protected _instruments: InstrumentsClient | undefined;
    protected _orders: OrdersClient | undefined;
    protected _pies: PiesClient | undefined;
    protected _positions: PositionsClient | undefined;

    constructor(options: Trading212Client.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get account(): AccountClient {
        return (this._account ??= new AccountClient(this._options));
    }

    public get history(): HistoryClient {
        return (this._history ??= new HistoryClient(this._options));
    }

    public get instruments(): InstrumentsClient {
        return (this._instruments ??= new InstrumentsClient(this._options));
    }

    public get orders(): OrdersClient {
        return (this._orders ??= new OrdersClient(this._options));
    }

    public get pies(): PiesClient {
        return (this._pies ??= new PiesClient(this._options));
    }

    public get positions(): PositionsClient {
        return (this._positions ??= new PositionsClient(this._options));
    }

    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    public async fetch(
        input: Request | string | URL,
        init?: RequestInit,
        requestOptions?: core.PassthroughRequest.RequestOptions,
    ): Promise<Response> {
        return core.makePassthroughRequest(
            input,
            init,
            {
                baseUrl: this._options.baseUrl ?? this._options.environment,
                headers: this._options.headers,
                timeoutInSeconds: this._options.timeoutInSeconds,
                maxRetries: this._options.maxRetries,
                fetch: this._options.fetch,
                logging: this._options.logging,
                getAuthHeaders: async () => (await this._options.authProvider.getAuthRequest()).headers,
            },
            requestOptions,
        );
    }
}
