// This file was auto-generated by Fern from our API Definition.

export const Trading212Environment = {
    Demo: "https://demo.trading212.com",
    Live: "https://live.trading212.com",
} as const;

export type Trading212Environment = typeof Trading212Environment.Demo | typeof Trading212Environment.Live;
