// This file was auto-generated by Fern from our API Definition.

import type * as Trading212 from "../index.js";

export interface AccountBucketInstrumentResult {
    currentShare?: number | undefined;
    expectedShare?: number | undefined;
    issues?: Trading212.InstrumentIssue[] | undefined;
    ownedQuantity?: number | undefined;
    result?: Trading212.InvestmentResult | undefined;
    ticker?: string | undefined;
}
