// This file was auto-generated by Fern from our API Definition.

import type * as Trading212 from "../index.js";

export interface AccountSummary {
    cash?: Trading212.Cash | undefined;
    /** Primary account currency in ISO 4217 format. */
    currency?: string | undefined;
    /** Primary trading account number. This is the same account ID you would see in the Trading 212 web or mobile application. */
    id?: number | undefined;
    investments?: Trading212.Investments | undefined;
    /** Investments value in your account's primary currency. */
    totalValue?: number | undefined;
}
