// This file was auto-generated by Fern from our API Definition.

export interface AccountBucketDetailedResponse {
    creationDate?: string | undefined;
    dividendCashAction?: AccountBucketDetailedResponse.DividendCashAction | undefined;
    endDate?: string | undefined;
    goal?: number | undefined;
    icon?: string | undefined;
    id?: number | undefined;
    initialInvestment?: number | undefined;
    instrumentShares?: Record<string, number> | undefined;
    name?: string | undefined;
    publicUrl?: string | undefined;
}

export namespace AccountBucketDetailedResponse {
    export const DividendCashAction = {
        Reinvest: "REINVEST",
        ToAccountCash: "TO_ACCOUNT_CASH",
    } as const;
    export type DividendCashAction = (typeof DividendCashAction)[keyof typeof DividendCashAction];
}
