// This file was auto-generated by Fern from our API Definition.

import type * as Trading212 from "../index.js";

export interface AccountBucketInstrumentsDetailedResponse {
    instruments?: Trading212.AccountBucketInstrumentResult[] | undefined;
    settings?: Trading212.AccountBucketDetailedResponse | undefined;
}
