// This file was auto-generated by Fern from our API Definition.

import type * as Trading212 from "../index.js";

export interface AccountBucketResultResponse {
    /** Amount of money put into the pie in account currency */
    cash?: number | undefined;
    dividendDetails?: Trading212.DividendDetails | undefined;
    id?: number | undefined;
    /** Progress of the pie based on the set goal */
    progress?: number | undefined;
    result?: Trading212.InvestmentResult | undefined;
    /** Status of the pie based on the set goal */
    status?: AccountBucketResultResponse.Status | undefined;
}

export namespace AccountBucketResultResponse {
    /** Status of the pie based on the set goal */
    export const Status = {
        Ahead: "AHEAD",
        OnTrack: "ON_TRACK",
        Behind: "BEHIND",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
