// This file was auto-generated by Fern from our API Definition.

export interface Cash {
    /** Funds available for investing. */
    availableToTrade?: number | undefined;
    /** It’s the sum of the cash inside of all pies that is not yet invested. */
    inPies?: number | undefined;
    /** The amount of cash reserved for pending orders. This cash is not available for placing new trades. */
    reservedForOrders?: number | undefined;
}
