// This file was auto-generated by Fern from our API Definition.

export interface DividendDetails {
    gained?: number | undefined;
    inCash?: number | undefined;
    reinvested?: number | undefined;
}
