// This file was auto-generated by Fern from our API Definition.

import type * as Trading212 from "../index.js";

export interface Exchange {
    id?: number | undefined;
    name?: string | undefined;
    workingSchedules?: Trading212.WorkingSchedule[] | undefined;
}
