// This file was auto-generated by Fern from our API Definition.

import type * as Trading212 from "../index.js";

export interface FillWalletImpact {
    currency?: string | undefined;
    fxRate?: number | undefined;
    netValue?: number | undefined;
    realisedProfitLoss?: number | undefined;
    taxes?: Trading212.Tax[] | undefined;
}
