// This file was auto-generated by Fern from our API Definition.

import type * as Trading212 from "../index.js";

export interface Fill {
    filledAt?: string | undefined;
    id?: number | undefined;
    price?: number | undefined;
    quantity?: number | undefined;
    tradingMethod?: Fill.TradingMethod | undefined;
    type?: Fill.Type | undefined;
    walletImpact?: Trading212.FillWalletImpact | undefined;
}

export namespace Fill {
    export const TradingMethod = {
        Totv: "TOTV",
        Otc: "OTC",
    } as const;
    export type TradingMethod = (typeof TradingMethod)[keyof typeof TradingMethod];
    export const Type = {
        Trade: "TRADE",
        StockSplit: "STOCK_SPLIT",
        StockDistribution: "STOCK_DISTRIBUTION",
        Fop: "FOP",
        FopCorrection: "FOP_CORRECTION",
        CustomStockDistribution: "CUSTOM_STOCK_DISTRIBUTION",
        EquityRights: "EQUITY_RIGHTS",
        ScripStockDividends: "SCRIP_STOCK_DIVIDENDS",
        StockDividends: "STOCK_DIVIDENDS",
        StockAcquisition: "STOCK_ACQUISITION",
        CashAndStockAcquisition: "CASH_AND_STOCK_ACQUISITION",
        SpinOff: "SPIN_OFF",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
