// This file was auto-generated by Fern from our API Definition.

import type * as Trading212 from "../index.js";

export interface HistoricalOrder {
    fill?: Trading212.Fill | undefined;
    order?: Trading212.Order | undefined;
}
