// This file was auto-generated by Fern from our API Definition.

import type * as Trading212 from "../index.js";

export interface HistoryDividendItem {
    /** In account's primary currency. */
    amount?: number | undefined;
    amountInEuro?: number | undefined;
    /** The account's primary currency. */
    currency?: string | undefined;
    /** In instrument currency */
    grossAmountPerShare?: number | undefined;
    instrument?: Trading212.Instrument | undefined;
    paidOn?: string | undefined;
    quantity?: number | undefined;
    reference?: string | undefined;
    ticker?: string | undefined;
    tickerCurrency?: string | undefined;
    type?: HistoryDividendItem.Type | undefined;
}

export namespace HistoryDividendItem {
    export const Type = {
        Ordinary: "ORDINARY",
        Bonus: "BONUS",
        PropertyIncome: "PROPERTY_INCOME",
        ReturnOfCapitalNonUs: "RETURN_OF_CAPITAL_NON_US",
        Demerger: "DEMERGER",
        Interest: "INTEREST",
        CapitalGainsDistributionNonUs: "CAPITAL_GAINS_DISTRIBUTION_NON_US",
        InterimLiquidation: "INTERIM_LIQUIDATION",
        OrdinaryManufacturedPayment: "ORDINARY_MANUFACTURED_PAYMENT",
        BonusManufacturedPayment: "BONUS_MANUFACTURED_PAYMENT",
        PropertyIncomeManufacturedPayment: "PROPERTY_INCOME_MANUFACTURED_PAYMENT",
        ReturnOfCapitalNonUsManufacturedPayment: "RETURN_OF_CAPITAL_NON_US_MANUFACTURED_PAYMENT",
        DemergerManufacturedPayment: "DEMERGER_MANUFACTURED_PAYMENT",
        InterestManufacturedPayment: "INTEREST_MANUFACTURED_PAYMENT",
        CapitalGainsDistributionNonUsManufacturedPayment: "CAPITAL_GAINS_DISTRIBUTION_NON_US_MANUFACTURED_PAYMENT",
        InterimLiquidationManufacturedPayment: "INTERIM_LIQUIDATION_MANUFACTURED_PAYMENT",
        InterestPaidByUsObligors: "INTEREST_PAID_BY_US_OBLIGORS",
        InterestPaidByForeignCorporations: "INTEREST_PAID_BY_FOREIGN_CORPORATIONS",
        DividendsPaidByUsCorporations: "DIVIDENDS_PAID_BY_US_CORPORATIONS",
        DividendsPaidByForeignCorporations: "DIVIDENDS_PAID_BY_FOREIGN_CORPORATIONS",
        CapitalGains: "CAPITAL_GAINS",
        RealPropertyIncomeAndNaturalResourcesRoyalties: "REAL_PROPERTY_INCOME_AND_NATURAL_RESOURCES_ROYALTIES",
        OtherIncome: "OTHER_INCOME",
        QualifiedInvestmentEntity: "QUALIFIED_INVESTMENT_ENTITY",
        TrustDistribution: "TRUST_DISTRIBUTION",
        PubliclyTradedPartnershipDistribution: "PUBLICLY_TRADED_PARTNERSHIP_DISTRIBUTION",
        CapitalGainsDistribution: "CAPITAL_GAINS_DISTRIBUTION",
        ReturnOfCapital: "RETURN_OF_CAPITAL",
        OtherDividendEquivalent: "OTHER_DIVIDEND_EQUIVALENT",
        TaxEvent1446FForPubliclyTradedSecurities: "TAX_EVENT_1446F_FOR_PUBLICLY_TRADED_SECURITIES",
        PtpUncharacterisedIncome: "PTP_UNCHARACTERISED_INCOME",
        Multiple1042STaxComponents: "MULTIPLE_1042S_TAX_COMPONENTS",
        Dividend: "DIVIDEND",
        ShortTermCapitalGains: "SHORT_TERM_CAPITAL_GAINS",
        LongTermCapitalGains: "LONG_TERM_CAPITAL_GAINS",
        PropertyIncomeDistribution: "PROPERTY_INCOME_DISTRIBUTION",
        TaxExempted: "TAX_EXEMPTED",
        InterestPaidByUsObligorsManufacturedPayment: "INTEREST_PAID_BY_US_OBLIGORS_MANUFACTURED_PAYMENT",
        InterestPaidByForeignCorporationsManufacturedPayment:
            "INTEREST_PAID_BY_FOREIGN_CORPORATIONS_MANUFACTURED_PAYMENT",
        DividendsPaidByUsCorporationsManufacturedPayment: "DIVIDENDS_PAID_BY_US_CORPORATIONS_MANUFACTURED_PAYMENT",
        DividendsPaidByForeignCorporationsManufacturedPayment:
            "DIVIDENDS_PAID_BY_FOREIGN_CORPORATIONS_MANUFACTURED_PAYMENT",
        CapitalGainsManufacturedPayment: "CAPITAL_GAINS_MANUFACTURED_PAYMENT",
        RealPropertyIncomeAndNaturalResourcesRoyaltiesManufacturedPayment:
            "REAL_PROPERTY_INCOME_AND_NATURAL_RESOURCES_ROYALTIES_MANUFACTURED_PAYMENT",
        OtherIncomeManufacturedPayment: "OTHER_INCOME_MANUFACTURED_PAYMENT",
        QualifiedInvestmentEntityManufacturedPayment: "QUALIFIED_INVESTMENT_ENTITY_MANUFACTURED_PAYMENT",
        TrustDistributionManufacturedPayment: "TRUST_DISTRIBUTION_MANUFACTURED_PAYMENT",
        PubliclyTradedPartnershipDistributionManufacturedPayment:
            "PUBLICLY_TRADED_PARTNERSHIP_DISTRIBUTION_MANUFACTURED_PAYMENT",
        CapitalGainsDistributionManufacturedPayment: "CAPITAL_GAINS_DISTRIBUTION_MANUFACTURED_PAYMENT",
        ReturnOfCapitalManufacturedPayment: "RETURN_OF_CAPITAL_MANUFACTURED_PAYMENT",
        OtherDividendEquivalentManufacturedPayment: "OTHER_DIVIDEND_EQUIVALENT_MANUFACTURED_PAYMENT",
        TaxEvent1446FForPubliclyTradedSecuritiesManufacturedPayment:
            "TAX_EVENT_1446F_FOR_PUBLICLY_TRADED_SECURITIES_MANUFACTURED_PAYMENT",
        PtpUncharacterisedIncomeManufacturedPayment: "PTP_UNCHARACTERISED_INCOME_MANUFACTURED_PAYMENT",
        Multiple1042STaxComponentsManufacturedPayment: "MULTIPLE_1042S_TAX_COMPONENTS_MANUFACTURED_PAYMENT",
        DividendManufacturedPayment: "DIVIDEND_MANUFACTURED_PAYMENT",
        ShortTermCapitalGainsManufacturedPayment: "SHORT_TERM_CAPITAL_GAINS_MANUFACTURED_PAYMENT",
        LongTermCapitalGainsManufacturedPayment: "LONG_TERM_CAPITAL_GAINS_MANUFACTURED_PAYMENT",
        PropertyIncomeDistributionManufacturedPayment: "PROPERTY_INCOME_DISTRIBUTION_MANUFACTURED_PAYMENT",
        TaxExemptedManufacturedPayment: "TAX_EXEMPTED_MANUFACTURED_PAYMENT",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
