// This file was auto-generated by Fern from our API Definition.

/**
 * Instrument information as given by /instruments endpoint.
 */
export interface Instrument {
    /** Instrument currency in ISO 4217 format. */
    currency?: string | undefined;
    /** ISIN of the instrument. */
    isin?: string | undefined;
    /** Name of the instrument. */
    name?: string | undefined;
    /** Unique instrument identifier. */
    ticker?: string | undefined;
}
