// This file was auto-generated by Fern from our API Definition.

export interface InstrumentIssue {
    name?: InstrumentIssue.Name | undefined;
    severity?: InstrumentIssue.Severity | undefined;
}

export namespace InstrumentIssue {
    export const Name = {
        Delisted: "DELISTED",
        Suspended: "SUSPENDED",
        NoLongerTradable: "NO_LONGER_TRADABLE",
        MaxPositionSizeReached: "MAX_POSITION_SIZE_REACHED",
        ApproachingMaxPositionSize: "APPROACHING_MAX_POSITION_SIZE",
        ComplexInstrumentAppTestRequired: "COMPLEX_INSTRUMENT_APP_TEST_REQUIRED",
        PriceTooLow: "PRICE_TOO_LOW",
    } as const;
    export type Name = (typeof Name)[keyof typeof Name];
    export const Severity = {
        Irreversible: "IRREVERSIBLE",
        Reversible: "REVERSIBLE",
        Informative: "INFORMATIVE",
    } as const;
    export type Severity = (typeof Severity)[keyof typeof Severity];
}
