// This file was auto-generated by Fern from our API Definition.

export interface Investments {
    /** Current value of all the investments. */
    currentValue?: number | undefined;
    /** The all-time realised profit loss from all of the trades executed. */
    realizedProfitLoss?: number | undefined;
    /** The cost basis of your current investments. The total amount of funds you've invested in the shares you currently own. */
    totalCost?: number | undefined;
    /** The potential profit/loss of your current investments, showing how much you could gain or lose if you were to sell them now. */
    unrealizedProfitLoss?: number | undefined;
}
