// This file was auto-generated by Fern from our API Definition.

import type * as Trading212 from "../index.js";

export interface Order {
    /** The ISO 8601 formatted date of when the order was created. */
    createdAt?: string | undefined;
    /** The currency used for the order in ISO 4217 format. */
    currency?: string | undefined;
    /** If true, the order is eligible for execution outside regular trading hours. */
    extendedHours?: boolean | undefined;
    /** The number of shares that have been successfully executed. Applicable to quantity orders. */
    filledQuantity?: number | undefined;
    /** The total monetary value of the executed portion of the order. Applicable to orders placed by value.Note: Placing orders by value is not currently supported via the API but can be done through other Trading 212 platforms. */
    filledValue?: number | undefined;
    /** A unique, system-generated identifier for the order. */
    id?: number | undefined;
    /** How the order was initiated. */
    initiatedFrom?: Order.InitiatedFrom | undefined;
    instrument?: Trading212.Instrument | undefined;
    /** Applicable to LIMIT and STOP_LIMIT orders. */
    limitPrice?: number | undefined;
    /** The total number of shares requested. Applicable to quantity orders. */
    quantity?: number | undefined;
    /** Indicates whether the order is BUY or SELL. */
    side?: Order.Side | undefined;
    /** The current state of the order in its lifecycle. */
    status?: Order.Status | undefined;
    /** Applicable to STOP and STOP_LIMIT orders. */
    stopPrice?: number | undefined;
    /** The strategy used to place the order, either by QUANTITY or VALUE. The API currently only supports placing orders by QUANTITY. */
    strategy?: Order.Strategy | undefined;
    /** Unique instrument identifier. Get from the /instruments endpoint */
    ticker?: string | undefined;
    timeInForce?: Trading212.TimeValidity | undefined;
    type?: Order.Type | undefined;
    /** The total monetary value of the order. Applicable to value orders. */
    value?: number | undefined;
}

export namespace Order {
    /** How the order was initiated. */
    export const InitiatedFrom = {
        Api: "API",
        Ios: "IOS",
        Android: "ANDROID",
        Web: "WEB",
        System: "SYSTEM",
        Autoinvest: "AUTOINVEST",
        InstrumentAutoinvest: "INSTRUMENT_AUTOINVEST",
    } as const;
    export type InitiatedFrom = (typeof InitiatedFrom)[keyof typeof InitiatedFrom];
    /** Indicates whether the order is BUY or SELL. */
    export const Side = {
        Buy: "BUY",
        Sell: "SELL",
    } as const;
    export type Side = (typeof Side)[keyof typeof Side];
    /** The current state of the order in its lifecycle. */
    export const Status = {
        Local: "LOCAL",
        Unconfirmed: "UNCONFIRMED",
        Confirmed: "CONFIRMED",
        New: "NEW",
        Cancelling: "CANCELLING",
        Cancelled: "CANCELLED",
        PartiallyFilled: "PARTIALLY_FILLED",
        Filled: "FILLED",
        Rejected: "REJECTED",
        Replacing: "REPLACING",
        Replaced: "REPLACED",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
    /** The strategy used to place the order, either by QUANTITY or VALUE. The API currently only supports placing orders by QUANTITY. */
    export const Strategy = {
        Quantity: "QUANTITY",
        Value: "VALUE",
    } as const;
    export type Strategy = (typeof Strategy)[keyof typeof Strategy];
    export const Type = {
        Limit: "LIMIT",
        Stop: "STOP",
        Market: "MARKET",
        StopLimit: "STOP_LIMIT",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
