// This file was auto-generated by Fern from our API Definition.

import type * as Trading212 from "../index.js";

export interface PaginatedResponseHistoricalOrder {
    items?: Trading212.HistoricalOrder[] | undefined;
    nextPagePath?: string | undefined;
}
