// This file was auto-generated by Fern from our API Definition.

import type * as Trading212 from "../index.js";

export interface PaginatedResponseHistoryTransactionItem {
    items?: Trading212.HistoryTransactionItem[] | undefined;
    nextPagePath?: string | undefined;
}
