// This file was auto-generated by Fern from our API Definition.

import type * as Trading212 from "../index.js";

export interface PaginatedResponseHistoryDividendItem {
    items?: Trading212.HistoryDividendItem[] | undefined;
    nextPagePath?: string | undefined;
}
