// This file was auto-generated by Fern from our API Definition.

export interface PieRequest {
    dividendCashAction?: PieRequest.DividendCashAction | undefined;
    endDate?: string | undefined;
    /** Total desired value of the pie in account currency */
    goal?: number | undefined;
    icon?: string | undefined;
    instrumentShares?: Record<string, number> | undefined;
    name?: string | undefined;
}

export namespace PieRequest {
    export const DividendCashAction = {
        Reinvest: "REINVEST",
        ToAccountCash: "TO_ACCOUNT_CASH",
    } as const;
    export type DividendCashAction = (typeof DividendCashAction)[keyof typeof DividendCashAction];
}
