// This file was auto-generated by Fern from our API Definition.

export interface PositionWalletImpact {
    /** The currency code used to represent all the wallet impact information. */
    currency?: string | undefined;
    /** The current market value of the position. */
    currentValue?: number | undefined;
    /** The positive or negative impact on the position's value due to currency rate changes. Only applies to positions with instrument currency that differs from the accounts. */
    fxImpact?: number | undefined;
    /** The total cost paid for the position. */
    totalCost?: number | undefined;
    /** The unrealized profit & loss for the position. Calculated as currentValue - totalCost. */
    unrealizedProfitLoss?: number | undefined;
}
