// This file was auto-generated by Fern from our API Definition.

import type * as Trading212 from "../index.js";

export interface Position {
    /** Average price paid, in instrument currency, per share. */
    averagePricePaid?: number | undefined;
    /** The ISO 8601 formatted date of when the position was opened. */
    createdAt?: string | undefined;
    /** Current price, in instrument currency, of a single share. */
    currentPrice?: number | undefined;
    instrument?: Trading212.Instrument | undefined;
    /** Total quantity of shares owned. */
    quantity?: number | undefined;
    /** Quantity of shares available for trading. */
    quantityAvailableForTrading?: number | undefined;
    /** Quantity of shares currently used in pie. */
    quantityInPies?: number | undefined;
    /** Collects the financial impact of the position on the user's wallet. */
    walletImpact?: Trading212.PositionWalletImpact | undefined;
}
