// This file was auto-generated by Fern from our API Definition.

export interface Tax {
    chargedAt?: string | undefined;
    currency?: string | undefined;
    name?: Tax.Name | undefined;
    quantity?: number | undefined;
}

export namespace Tax {
    export const Name = {
        CommissionTurnover: "COMMISSION_TURNOVER",
        CurrencyConversionFee: "CURRENCY_CONVERSION_FEE",
        FinraFee: "FINRA_FEE",
        FrenchTransactionTax: "FRENCH_TRANSACTION_TAX",
        PtmLevy: "PTM_LEVY",
        StampDuty: "STAMP_DUTY",
        StampDutyReserveTax: "STAMP_DUTY_RESERVE_TAX",
        TransactionFee: "TRANSACTION_FEE",
    } as const;
    export type Name = (typeof Name)[keyof typeof Name];
}
