// This file was auto-generated by Fern from our API Definition.

export interface TimeEvent {
    date?: string | undefined;
    type?: TimeEvent.Type | undefined;
}

export namespace TimeEvent {
    export const Type = {
        Open: "OPEN",
        Close: "CLOSE",
        BreakStart: "BREAK_START",
        BreakEnd: "BREAK_END",
        PreMarketOpen: "PRE_MARKET_OPEN",
        AfterHoursOpen: "AFTER_HOURS_OPEN",
        AfterHoursClose: "AFTER_HOURS_CLOSE",
        OvernightOpen: "OVERNIGHT_OPEN",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
