// This file was auto-generated by Fern from our API Definition.

/**
 * Specifies how long the order remains active:
 * * DAY: The order will automatically expire if not executed by midnight in the time zone of the instrument's exchange.
 * * GOOD_TILL_CANCEL: The order remains active indefinitely until it is either filled or explicitly cancelled by you.
 */
export const TimeValidity = {
    Day: "DAY",
    GoodTillCancel: "GOOD_TILL_CANCEL",
} as const;
export type TimeValidity = (typeof TimeValidity)[keyof typeof TimeValidity];
