// This file was auto-generated by Fern from our API Definition.

export interface TradableInstrument {
    /** On the platform since */
    addedOn?: string | undefined;
    /** ISO 4217 */
    currencyCode?: string | undefined;
    extendedHours?: boolean | undefined;
    isin?: string | undefined;
    maxOpenQuantity?: number | undefined;
    name?: string | undefined;
    shortName?: string | undefined;
    /** Unique identifier */
    ticker?: string | undefined;
    type?: TradableInstrument.Type | undefined;
    /** Get items in the /exchanges endpoint */
    workingScheduleId?: number | undefined;
}

export namespace TradableInstrument {
    export const Type = {
        Cryptocurrency: "CRYPTOCURRENCY",
        Etf: "ETF",
        Forex: "FOREX",
        Futures: "FUTURES",
        Index: "INDEX",
        Stock: "STOCK",
        Warrant: "WARRANT",
        Crypto: "CRYPTO",
        Cvr: "CVR",
        Corpact: "CORPACT",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
