// This file was auto-generated by Fern from our API Definition.

import type * as Trading212 from "../index.js";

export interface WorkingSchedule {
    id?: number | undefined;
    timeEvents?: Trading212.TimeEvent[] | undefined;
}
