# This file was auto-generated by Fern from our API Definition.

import warnings
import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.account_bucket_instruments_detailed_response import AccountBucketInstrumentsDetailedResponse
from ..types.account_bucket_result_response import AccountBucketResultResponse
from ..types.pie_request_dividend_cash_action import PieRequestDividendCashAction
from .raw_client import AsyncRawPiesClient, RawPiesClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class PiesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawPiesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawPiesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPiesClient
        """
        return self._raw_client

    def list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[AccountBucketResultResponse]:
        """
        Fetches all pies for the account

        **Rate limit:** 1 req / 30s

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[AccountBucketResultResponse]
            OK

        Examples
        --------
        from t212 import Trading212Client

        client = Trading212Client(
            api_key="YOUR_API_KEY",
            api_secret="YOUR_API_SECRET",
        )
        client.pies.list()
        """
        warnings.warn('pies.list is deprecated. The Pies API is no longer supported or updated by Trading 212.', DeprecationWarning, stacklevel=2)  # t212: deprecation warning
        _response = self._raw_client.list(request_options=request_options)
        return _response.data

    def create(
        self,
        *,
        dividend_cash_action: typing.Optional[PieRequestDividendCashAction] = OMIT,
        end_date: typing.Optional[dt.datetime] = OMIT,
        goal: typing.Optional[float] = OMIT,
        icon: typing.Optional[str] = OMIT,
        instrument_shares: typing.Optional[typing.Dict[str, float]] = OMIT,
        name: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AccountBucketInstrumentsDetailedResponse:
        """
        Creates a pie for the account by given params

        **Rate limit:** 1 req / 5s

        Parameters
        ----------
        dividend_cash_action : typing.Optional[PieRequestDividendCashAction]

        end_date : typing.Optional[dt.datetime]

        goal : typing.Optional[float]
            Total desired value of the pie in account currency

        icon : typing.Optional[str]

        instrument_shares : typing.Optional[typing.Dict[str, float]]

        name : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AccountBucketInstrumentsDetailedResponse
            OK

        Examples
        --------
        from t212 import Trading212Client

        client = Trading212Client(
            api_key="YOUR_API_KEY",
            api_secret="YOUR_API_SECRET",
        )
        client.pies.create()
        """
        warnings.warn('pies.create is deprecated. The Pies API is no longer supported or updated by Trading 212.', DeprecationWarning, stacklevel=2)  # t212: deprecation warning
        _response = self._raw_client.create(
            dividend_cash_action=dividend_cash_action,
            end_date=end_date,
            goal=goal,
            icon=icon,
            instrument_shares=instrument_shares,
            name=name,
            request_options=request_options,
        )
        return _response.data

    def get(
        self, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AccountBucketInstrumentsDetailedResponse:
        """
        Fetches a pies for the account with detailed information

        **Rate limit:** 1 req / 5s

        Parameters
        ----------
        id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AccountBucketInstrumentsDetailedResponse
            OK

        Examples
        --------
        from t212 import Trading212Client

        client = Trading212Client(
            api_key="YOUR_API_KEY",
            api_secret="YOUR_API_SECRET",
        )
        client.pies.get(
            id=1000000,
        )
        """
        warnings.warn('pies.get is deprecated. The Pies API is no longer supported or updated by Trading 212.', DeprecationWarning, stacklevel=2)  # t212: deprecation warning
        _response = self._raw_client.get(id, request_options=request_options)
        return _response.data

    def update(
        self,
        id: int,
        *,
        dividend_cash_action: typing.Optional[PieRequestDividendCashAction] = OMIT,
        end_date: typing.Optional[dt.datetime] = OMIT,
        goal: typing.Optional[float] = OMIT,
        icon: typing.Optional[str] = OMIT,
        instrument_shares: typing.Optional[typing.Dict[str, float]] = OMIT,
        name: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AccountBucketInstrumentsDetailedResponse:
        """
        Updates a pie for the account by given params

        **Rate limit:** 1 req / 5s

        Parameters
        ----------
        id : int

        dividend_cash_action : typing.Optional[PieRequestDividendCashAction]

        end_date : typing.Optional[dt.datetime]

        goal : typing.Optional[float]
            Total desired value of the pie in account currency

        icon : typing.Optional[str]

        instrument_shares : typing.Optional[typing.Dict[str, float]]

        name : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AccountBucketInstrumentsDetailedResponse
            OK

        Examples
        --------
        from t212 import Trading212Client

        client = Trading212Client(
            api_key="YOUR_API_KEY",
            api_secret="YOUR_API_SECRET",
        )
        client.pies.update(
            id=1000000,
        )
        """
        warnings.warn('pies.update is deprecated. The Pies API is no longer supported or updated by Trading 212.', DeprecationWarning, stacklevel=2)  # t212: deprecation warning
        _response = self._raw_client.update(
            id,
            dividend_cash_action=dividend_cash_action,
            end_date=end_date,
            goal=goal,
            icon=icon,
            instrument_shares=instrument_shares,
            name=name,
            request_options=request_options,
        )
        return _response.data

    def delete(self, id: int, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Deletes a pie by given id

        **Rate limit:** 1 req / 5s

        Parameters
        ----------
        id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from t212 import Trading212Client

        client = Trading212Client(
            api_key="YOUR_API_KEY",
            api_secret="YOUR_API_SECRET",
        )
        client.pies.delete(
            id=1000000,
        )
        """
        warnings.warn('pies.delete is deprecated. The Pies API is no longer supported or updated by Trading 212.', DeprecationWarning, stacklevel=2)  # t212: deprecation warning
        _response = self._raw_client.delete(id, request_options=request_options)
        return _response.data

    def duplicate(
        self,
        id: int,
        *,
        icon: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AccountBucketInstrumentsDetailedResponse:
        """
        Duplicates a pie for the account

        **Rate limit:** 1 req / 5s

        Parameters
        ----------
        id : int

        icon : typing.Optional[str]

        name : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AccountBucketInstrumentsDetailedResponse
            OK

        Examples
        --------
        from t212 import Trading212Client

        client = Trading212Client(
            api_key="YOUR_API_KEY",
            api_secret="YOUR_API_SECRET",
        )
        client.pies.duplicate(
            id=1000000,
        )
        """
        warnings.warn('pies.duplicate is deprecated. The Pies API is no longer supported or updated by Trading 212.', DeprecationWarning, stacklevel=2)  # t212: deprecation warning
        _response = self._raw_client.duplicate(id, icon=icon, name=name, request_options=request_options)
        return _response.data


class AsyncPiesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawPiesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawPiesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPiesClient
        """
        return self._raw_client

    async def list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[AccountBucketResultResponse]:
        """
        Fetches all pies for the account

        **Rate limit:** 1 req / 30s

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[AccountBucketResultResponse]
            OK

        Examples
        --------
        import asyncio

        from t212 import AsyncTrading212Client

        client = AsyncTrading212Client(
            api_key="YOUR_API_KEY",
            api_secret="YOUR_API_SECRET",
        )


        async def main() -> None:
            await client.pies.list()


        asyncio.run(main())
        """
        warnings.warn('pies.list is deprecated. The Pies API is no longer supported or updated by Trading 212.', DeprecationWarning, stacklevel=2)  # t212: deprecation warning
        _response = await self._raw_client.list(request_options=request_options)
        return _response.data

    async def create(
        self,
        *,
        dividend_cash_action: typing.Optional[PieRequestDividendCashAction] = OMIT,
        end_date: typing.Optional[dt.datetime] = OMIT,
        goal: typing.Optional[float] = OMIT,
        icon: typing.Optional[str] = OMIT,
        instrument_shares: typing.Optional[typing.Dict[str, float]] = OMIT,
        name: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AccountBucketInstrumentsDetailedResponse:
        """
        Creates a pie for the account by given params

        **Rate limit:** 1 req / 5s

        Parameters
        ----------
        dividend_cash_action : typing.Optional[PieRequestDividendCashAction]

        end_date : typing.Optional[dt.datetime]

        goal : typing.Optional[float]
            Total desired value of the pie in account currency

        icon : typing.Optional[str]

        instrument_shares : typing.Optional[typing.Dict[str, float]]

        name : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AccountBucketInstrumentsDetailedResponse
            OK

        Examples
        --------
        import asyncio

        from t212 import AsyncTrading212Client

        client = AsyncTrading212Client(
            api_key="YOUR_API_KEY",
            api_secret="YOUR_API_SECRET",
        )


        async def main() -> None:
            await client.pies.create()


        asyncio.run(main())
        """
        warnings.warn('pies.create is deprecated. The Pies API is no longer supported or updated by Trading 212.', DeprecationWarning, stacklevel=2)  # t212: deprecation warning
        _response = await self._raw_client.create(
            dividend_cash_action=dividend_cash_action,
            end_date=end_date,
            goal=goal,
            icon=icon,
            instrument_shares=instrument_shares,
            name=name,
            request_options=request_options,
        )
        return _response.data

    async def get(
        self, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AccountBucketInstrumentsDetailedResponse:
        """
        Fetches a pies for the account with detailed information

        **Rate limit:** 1 req / 5s

        Parameters
        ----------
        id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AccountBucketInstrumentsDetailedResponse
            OK

        Examples
        --------
        import asyncio

        from t212 import AsyncTrading212Client

        client = AsyncTrading212Client(
            api_key="YOUR_API_KEY",
            api_secret="YOUR_API_SECRET",
        )


        async def main() -> None:
            await client.pies.get(
                id=1000000,
            )


        asyncio.run(main())
        """
        warnings.warn('pies.get is deprecated. The Pies API is no longer supported or updated by Trading 212.', DeprecationWarning, stacklevel=2)  # t212: deprecation warning
        _response = await self._raw_client.get(id, request_options=request_options)
        return _response.data

    async def update(
        self,
        id: int,
        *,
        dividend_cash_action: typing.Optional[PieRequestDividendCashAction] = OMIT,
        end_date: typing.Optional[dt.datetime] = OMIT,
        goal: typing.Optional[float] = OMIT,
        icon: typing.Optional[str] = OMIT,
        instrument_shares: typing.Optional[typing.Dict[str, float]] = OMIT,
        name: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AccountBucketInstrumentsDetailedResponse:
        """
        Updates a pie for the account by given params

        **Rate limit:** 1 req / 5s

        Parameters
        ----------
        id : int

        dividend_cash_action : typing.Optional[PieRequestDividendCashAction]

        end_date : typing.Optional[dt.datetime]

        goal : typing.Optional[float]
            Total desired value of the pie in account currency

        icon : typing.Optional[str]

        instrument_shares : typing.Optional[typing.Dict[str, float]]

        name : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AccountBucketInstrumentsDetailedResponse
            OK

        Examples
        --------
        import asyncio

        from t212 import AsyncTrading212Client

        client = AsyncTrading212Client(
            api_key="YOUR_API_KEY",
            api_secret="YOUR_API_SECRET",
        )


        async def main() -> None:
            await client.pies.update(
                id=1000000,
            )


        asyncio.run(main())
        """
        warnings.warn('pies.update is deprecated. The Pies API is no longer supported or updated by Trading 212.', DeprecationWarning, stacklevel=2)  # t212: deprecation warning
        _response = await self._raw_client.update(
            id,
            dividend_cash_action=dividend_cash_action,
            end_date=end_date,
            goal=goal,
            icon=icon,
            instrument_shares=instrument_shares,
            name=name,
            request_options=request_options,
        )
        return _response.data

    async def delete(self, id: int, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Deletes a pie by given id

        **Rate limit:** 1 req / 5s

        Parameters
        ----------
        id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from t212 import AsyncTrading212Client

        client = AsyncTrading212Client(
            api_key="YOUR_API_KEY",
            api_secret="YOUR_API_SECRET",
        )


        async def main() -> None:
            await client.pies.delete(
                id=1000000,
            )


        asyncio.run(main())
        """
        warnings.warn('pies.delete is deprecated. The Pies API is no longer supported or updated by Trading 212.', DeprecationWarning, stacklevel=2)  # t212: deprecation warning
        _response = await self._raw_client.delete(id, request_options=request_options)
        return _response.data

    async def duplicate(
        self,
        id: int,
        *,
        icon: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AccountBucketInstrumentsDetailedResponse:
        """
        Duplicates a pie for the account

        **Rate limit:** 1 req / 5s

        Parameters
        ----------
        id : int

        icon : typing.Optional[str]

        name : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AccountBucketInstrumentsDetailedResponse
            OK

        Examples
        --------
        import asyncio

        from t212 import AsyncTrading212Client

        client = AsyncTrading212Client(
            api_key="YOUR_API_KEY",
            api_secret="YOUR_API_SECRET",
        )


        async def main() -> None:
            await client.pies.duplicate(
                id=1000000,
            )


        asyncio.run(main())
        """
        warnings.warn('pies.duplicate is deprecated. The Pies API is no longer supported or updated by Trading 212.', DeprecationWarning, stacklevel=2)  # t212: deprecation warning
        _response = await self._raw_client.duplicate(id, icon=icon, name=name, request_options=request_options)
        return _response.data
