# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.order import Order
from ..types.time_validity import TimeValidity
from .raw_client import AsyncRawOrdersClient, RawOrdersClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class OrdersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawOrdersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawOrdersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawOrdersClient
        """
        return self._raw_client

    def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.List[Order]:
        """
        Retrieves a list of all orders that are currently active (i.e., not yet
        filled, cancelled, or expired). This is useful for monitoring the status
        of your open positions and managing your trading strategy.

        **Rate limit:** 1 req / 5s

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[Order]
            OK

        Examples
        --------
        from t212 import Trading212Client

        client = Trading212Client(
            api_key="YOUR_API_KEY",
            api_secret="YOUR_API_SECRET",
        )
        client.orders.list()
        """
        _response = self._raw_client.list(request_options=request_options)
        return _response.data

    def place_limit(
        self,
        *,
        limit_price: typing.Optional[float] = OMIT,
        quantity: typing.Optional[float] = OMIT,
        ticker: typing.Optional[str] = OMIT,
        time_validity: typing.Optional[TimeValidity] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Order:
        """
        Creates a new Limit order, which executes at a specified price or
        better.

        - To place a **buy** order, use a positive `quantity`. The order will
        fill at the `limitPrice` or lower.

        - To place a **sell** order, use a negative `quantity`. The order will
        fill at the `limitPrice` or higher.



        **Order Limitations**

        * Orders can be executed only in the **main account currency**


        **Important:** In this beta version, this endpoint is **not
        idempotent**. Sending the same request multiple times may result in
        duplicate orders.

        **Rate limit:** 1 req / 2s

        Parameters
        ----------
        limit_price : typing.Optional[float]

        quantity : typing.Optional[float]

        ticker : typing.Optional[str]

        time_validity : typing.Optional[TimeValidity]
            Expiration

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Order
            OK

        Examples
        --------
        from t212 import Trading212Client

        client = Trading212Client(
            api_key="YOUR_API_KEY",
            api_secret="YOUR_API_SECRET",
        )
        client.orders.place_limit()
        """
        _response = self._raw_client.place_limit(
            limit_price=limit_price,
            quantity=quantity,
            ticker=ticker,
            time_validity=time_validity,
            request_options=request_options,
        )
        return _response.data

    def place_market(
        self,
        *,
        extended_hours: typing.Optional[bool] = OMIT,
        quantity: typing.Optional[float] = OMIT,
        ticker: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Order:
        """
        Creates a new Market order, which is an instruction to trade a security
        immediately at the next available price.

        - To place a **buy** order, use a positive `quantity`.

        - To place a **sell** order, use a negative `quantity`.


        - **`extendedHours`**: Set to `true` to allow the order to be filled
        outside of the standard trading session.

        - If placed when the market is closed, the order will be queued to
        execute when the market next opens.

        x
        **Order Limitations**

        * Orders can be executed only in the **main account currency**


        **Warning:** Market orders can be subject to price slippage, where the
        final execution price may differ from the price at the time of order
        placement.


        **Important:** In this beta version, this endpoint is **not
        idempotent**. Sending the same request multiple times may result in
        duplicate orders.

        **Rate limit:** 50 req / 1m0s

        Parameters
        ----------
        extended_hours : typing.Optional[bool]

        quantity : typing.Optional[float]

        ticker : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Order
            OK

        Examples
        --------
        from t212 import Trading212Client

        client = Trading212Client(
            api_key="YOUR_API_KEY",
            api_secret="YOUR_API_SECRET",
        )
        client.orders.place_market()
        """
        _response = self._raw_client.place_market(
            extended_hours=extended_hours, quantity=quantity, ticker=ticker, request_options=request_options
        )
        return _response.data

    def place_stop(
        self,
        *,
        quantity: typing.Optional[float] = OMIT,
        stop_price: typing.Optional[float] = OMIT,
        ticker: typing.Optional[str] = OMIT,
        time_validity: typing.Optional[TimeValidity] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Order:
        """
        Creates a new Stop order, which places a Market order once the
        `stopPrice` is reached.

        - To place a **buy** stop order, use a positive `quantity`.

        - To place a **sell** stop order (commonly a 'stop-loss'), use a
        negative `quantity`.


        - The `stopPrice` is triggered by the instrument's **Last Traded Price
        (LTP)**.




        **Order Limitations**

        * Orders can be executed only in the **main account currency**

        **Important:** In this beta version, this endpoint is **not
        idempotent**. Sending the same request multiple times may result in
        duplicate orders.

        **Rate limit:** 1 req / 2s

        Parameters
        ----------
        quantity : typing.Optional[float]

        stop_price : typing.Optional[float]

        ticker : typing.Optional[str]

        time_validity : typing.Optional[TimeValidity]
            Expiration

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Order
            OK

        Examples
        --------
        from t212 import Trading212Client

        client = Trading212Client(
            api_key="YOUR_API_KEY",
            api_secret="YOUR_API_SECRET",
        )
        client.orders.place_stop()
        """
        _response = self._raw_client.place_stop(
            quantity=quantity,
            stop_price=stop_price,
            ticker=ticker,
            time_validity=time_validity,
            request_options=request_options,
        )
        return _response.data

    def place_stop_limit(
        self,
        *,
        limit_price: typing.Optional[float] = OMIT,
        quantity: typing.Optional[float] = OMIT,
        stop_price: typing.Optional[float] = OMIT,
        ticker: typing.Optional[str] = OMIT,
        time_validity: typing.Optional[TimeValidity] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Order:
        """
        Creates a new Stop-Limit order, combining features of a Stop and a Limit
        order. The direction of the trade (buy/sell) is determined by the sign
        of the `quantity` field.


        **Execution Logic:**

        1.  When the instrument's **Last Traded Price (LTP)** reaches the
        specified `stopPrice`, the order is triggered.

        2.  A Limit order is then automatically placed at the specified
        `limitPrice`.


        This two-step process helps protect against price slippage that can
        occur with a standard Stop order.


        **Order Limitations**

        * Orders can be executed only in the **main account currency**


        **Important:** In this beta version, this endpoint is **not
        idempotent**. Sending the same request multiple times may result in
        duplicate orders.

        **Rate limit:** 1 req / 2s

        Parameters
        ----------
        limit_price : typing.Optional[float]

        quantity : typing.Optional[float]

        stop_price : typing.Optional[float]

        ticker : typing.Optional[str]

        time_validity : typing.Optional[TimeValidity]
            Expiration

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Order
            OK

        Examples
        --------
        from t212 import Trading212Client

        client = Trading212Client(
            api_key="YOUR_API_KEY",
            api_secret="YOUR_API_SECRET",
        )
        client.orders.place_stop_limit()
        """
        _response = self._raw_client.place_stop_limit(
            limit_price=limit_price,
            quantity=quantity,
            stop_price=stop_price,
            ticker=ticker,
            time_validity=time_validity,
            request_options=request_options,
        )
        return _response.data

    def get(self, id: int, *, request_options: typing.Optional[RequestOptions] = None) -> Order:
        """
        Retrieves a single pending order using its unique numerical ID. This is
        useful for checking the status of a specific order you have previously
        placed.

        **Rate limit:** 1 req / 1s

        Parameters
        ----------
        id : int
            The unique identifier of the order you want to retrieve.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Order
            Order found

        Examples
        --------
        from t212 import Trading212Client

        client = Trading212Client(
            api_key="YOUR_API_KEY",
            api_secret="YOUR_API_SECRET",
        )
        client.orders.get(
            id=1000000,
        )
        """
        _response = self._raw_client.get(id, request_options=request_options)
        return _response.data

    def cancel(self, id: int, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Attempts to cancel an active, unfilled order by its unique ID.
        Cancellation is not guaranteed if the order is already in the process of
        being filled. A successful response indicates the cancellation request
        was accepted.

        **Rate limit:** 50 req / 1m0s

        Parameters
        ----------
        id : int
            The unique identifier of the order you want to cancel.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from t212 import Trading212Client

        client = Trading212Client(
            api_key="YOUR_API_KEY",
            api_secret="YOUR_API_SECRET",
        )
        client.orders.cancel(
            id=1000000,
        )
        """
        _response = self._raw_client.cancel(id, request_options=request_options)
        return _response.data


class AsyncOrdersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawOrdersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawOrdersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawOrdersClient
        """
        return self._raw_client

    async def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.List[Order]:
        """
        Retrieves a list of all orders that are currently active (i.e., not yet
        filled, cancelled, or expired). This is useful for monitoring the status
        of your open positions and managing your trading strategy.

        **Rate limit:** 1 req / 5s

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[Order]
            OK

        Examples
        --------
        import asyncio

        from t212 import AsyncTrading212Client

        client = AsyncTrading212Client(
            api_key="YOUR_API_KEY",
            api_secret="YOUR_API_SECRET",
        )


        async def main() -> None:
            await client.orders.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(request_options=request_options)
        return _response.data

    async def place_limit(
        self,
        *,
        limit_price: typing.Optional[float] = OMIT,
        quantity: typing.Optional[float] = OMIT,
        ticker: typing.Optional[str] = OMIT,
        time_validity: typing.Optional[TimeValidity] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Order:
        """
        Creates a new Limit order, which executes at a specified price or
        better.

        - To place a **buy** order, use a positive `quantity`. The order will
        fill at the `limitPrice` or lower.

        - To place a **sell** order, use a negative `quantity`. The order will
        fill at the `limitPrice` or higher.



        **Order Limitations**

        * Orders can be executed only in the **main account currency**


        **Important:** In this beta version, this endpoint is **not
        idempotent**. Sending the same request multiple times may result in
        duplicate orders.

        **Rate limit:** 1 req / 2s

        Parameters
        ----------
        limit_price : typing.Optional[float]

        quantity : typing.Optional[float]

        ticker : typing.Optional[str]

        time_validity : typing.Optional[TimeValidity]
            Expiration

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Order
            OK

        Examples
        --------
        import asyncio

        from t212 import AsyncTrading212Client

        client = AsyncTrading212Client(
            api_key="YOUR_API_KEY",
            api_secret="YOUR_API_SECRET",
        )


        async def main() -> None:
            await client.orders.place_limit()


        asyncio.run(main())
        """
        _response = await self._raw_client.place_limit(
            limit_price=limit_price,
            quantity=quantity,
            ticker=ticker,
            time_validity=time_validity,
            request_options=request_options,
        )
        return _response.data

    async def place_market(
        self,
        *,
        extended_hours: typing.Optional[bool] = OMIT,
        quantity: typing.Optional[float] = OMIT,
        ticker: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Order:
        """
        Creates a new Market order, which is an instruction to trade a security
        immediately at the next available price.

        - To place a **buy** order, use a positive `quantity`.

        - To place a **sell** order, use a negative `quantity`.


        - **`extendedHours`**: Set to `true` to allow the order to be filled
        outside of the standard trading session.

        - If placed when the market is closed, the order will be queued to
        execute when the market next opens.

        x
        **Order Limitations**

        * Orders can be executed only in the **main account currency**


        **Warning:** Market orders can be subject to price slippage, where the
        final execution price may differ from the price at the time of order
        placement.


        **Important:** In this beta version, this endpoint is **not
        idempotent**. Sending the same request multiple times may result in
        duplicate orders.

        **Rate limit:** 50 req / 1m0s

        Parameters
        ----------
        extended_hours : typing.Optional[bool]

        quantity : typing.Optional[float]

        ticker : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Order
            OK

        Examples
        --------
        import asyncio

        from t212 import AsyncTrading212Client

        client = AsyncTrading212Client(
            api_key="YOUR_API_KEY",
            api_secret="YOUR_API_SECRET",
        )


        async def main() -> None:
            await client.orders.place_market()


        asyncio.run(main())
        """
        _response = await self._raw_client.place_market(
            extended_hours=extended_hours, quantity=quantity, ticker=ticker, request_options=request_options
        )
        return _response.data

    async def place_stop(
        self,
        *,
        quantity: typing.Optional[float] = OMIT,
        stop_price: typing.Optional[float] = OMIT,
        ticker: typing.Optional[str] = OMIT,
        time_validity: typing.Optional[TimeValidity] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Order:
        """
        Creates a new Stop order, which places a Market order once the
        `stopPrice` is reached.

        - To place a **buy** stop order, use a positive `quantity`.

        - To place a **sell** stop order (commonly a 'stop-loss'), use a
        negative `quantity`.


        - The `stopPrice` is triggered by the instrument's **Last Traded Price
        (LTP)**.




        **Order Limitations**

        * Orders can be executed only in the **main account currency**

        **Important:** In this beta version, this endpoint is **not
        idempotent**. Sending the same request multiple times may result in
        duplicate orders.

        **Rate limit:** 1 req / 2s

        Parameters
        ----------
        quantity : typing.Optional[float]

        stop_price : typing.Optional[float]

        ticker : typing.Optional[str]

        time_validity : typing.Optional[TimeValidity]
            Expiration

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Order
            OK

        Examples
        --------
        import asyncio

        from t212 import AsyncTrading212Client

        client = AsyncTrading212Client(
            api_key="YOUR_API_KEY",
            api_secret="YOUR_API_SECRET",
        )


        async def main() -> None:
            await client.orders.place_stop()


        asyncio.run(main())
        """
        _response = await self._raw_client.place_stop(
            quantity=quantity,
            stop_price=stop_price,
            ticker=ticker,
            time_validity=time_validity,
            request_options=request_options,
        )
        return _response.data

    async def place_stop_limit(
        self,
        *,
        limit_price: typing.Optional[float] = OMIT,
        quantity: typing.Optional[float] = OMIT,
        stop_price: typing.Optional[float] = OMIT,
        ticker: typing.Optional[str] = OMIT,
        time_validity: typing.Optional[TimeValidity] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Order:
        """
        Creates a new Stop-Limit order, combining features of a Stop and a Limit
        order. The direction of the trade (buy/sell) is determined by the sign
        of the `quantity` field.


        **Execution Logic:**

        1.  When the instrument's **Last Traded Price (LTP)** reaches the
        specified `stopPrice`, the order is triggered.

        2.  A Limit order is then automatically placed at the specified
        `limitPrice`.


        This two-step process helps protect against price slippage that can
        occur with a standard Stop order.


        **Order Limitations**

        * Orders can be executed only in the **main account currency**


        **Important:** In this beta version, this endpoint is **not
        idempotent**. Sending the same request multiple times may result in
        duplicate orders.

        **Rate limit:** 1 req / 2s

        Parameters
        ----------
        limit_price : typing.Optional[float]

        quantity : typing.Optional[float]

        stop_price : typing.Optional[float]

        ticker : typing.Optional[str]

        time_validity : typing.Optional[TimeValidity]
            Expiration

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Order
            OK

        Examples
        --------
        import asyncio

        from t212 import AsyncTrading212Client

        client = AsyncTrading212Client(
            api_key="YOUR_API_KEY",
            api_secret="YOUR_API_SECRET",
        )


        async def main() -> None:
            await client.orders.place_stop_limit()


        asyncio.run(main())
        """
        _response = await self._raw_client.place_stop_limit(
            limit_price=limit_price,
            quantity=quantity,
            stop_price=stop_price,
            ticker=ticker,
            time_validity=time_validity,
            request_options=request_options,
        )
        return _response.data

    async def get(self, id: int, *, request_options: typing.Optional[RequestOptions] = None) -> Order:
        """
        Retrieves a single pending order using its unique numerical ID. This is
        useful for checking the status of a specific order you have previously
        placed.

        **Rate limit:** 1 req / 1s

        Parameters
        ----------
        id : int
            The unique identifier of the order you want to retrieve.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Order
            Order found

        Examples
        --------
        import asyncio

        from t212 import AsyncTrading212Client

        client = AsyncTrading212Client(
            api_key="YOUR_API_KEY",
            api_secret="YOUR_API_SECRET",
        )


        async def main() -> None:
            await client.orders.get(
                id=1000000,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(id, request_options=request_options)
        return _response.data

    async def cancel(self, id: int, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Attempts to cancel an active, unfilled order by its unique ID.
        Cancellation is not guaranteed if the order is already in the process of
        being filled. A successful response indicates the cancellation request
        was accepted.

        **Rate limit:** 50 req / 1m0s

        Parameters
        ----------
        id : int
            The unique identifier of the order you want to cancel.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from t212 import AsyncTrading212Client

        client = AsyncTrading212Client(
            api_key="YOUR_API_KEY",
            api_secret="YOUR_API_SECRET",
        )


        async def main() -> None:
            await client.orders.cancel(
                id=1000000,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.cancel(id, request_options=request_options)
        return _response.data
