// This file was auto-generated by Fern from our API Definition.

import * as core from "../core/index.js";
import * as errors from "../errors/index.js";

const USERNAME_PARAM = "apiKey" as const;
const PASSWORD_PARAM = "apiSecret" as const;
const ENV_USERNAME = "T212_API_KEY" as const;
const ENV_PASSWORD = "T212_API_SECRET" as const;

export class BasicAuthProvider implements core.AuthProvider {
    private readonly options: BasicAuthProvider.Options;

    constructor(options: BasicAuthProvider.Options) {
        this.options = options;
    }

    public static canCreate(options: Partial<BasicAuthProvider.Options>): boolean {
        return (
            (options?.[USERNAME_PARAM] != null || process.env?.[ENV_USERNAME] != null) &&
            (options?.[PASSWORD_PARAM] != null || process.env?.[ENV_PASSWORD] != null)
        );
    }

    public async getAuthRequest({
        endpointMetadata,
    }: {
        endpointMetadata?: core.EndpointMetadata;
    } = {}): Promise<core.AuthRequest> {
        const apiKey = (await core.Supplier.get(this.options[USERNAME_PARAM])) ?? process.env?.[ENV_USERNAME];
        if (apiKey == null) {
            throw new errors.Trading212Error({ message: BasicAuthProvider.AUTH_CONFIG_ERROR_MESSAGE_USERNAME });
        }
        const apiSecret = (await core.Supplier.get(this.options[PASSWORD_PARAM])) ?? process.env?.[ENV_PASSWORD];
        if (apiSecret == null) {
            throw new errors.Trading212Error({ message: BasicAuthProvider.AUTH_CONFIG_ERROR_MESSAGE_PASSWORD });
        }

        const authHeader = core.BasicAuth.toAuthorizationHeader({
            username: apiKey,
            password: apiSecret,
        });

        return {
            headers: authHeader != null ? { Authorization: authHeader } : {},
        };
    }
}

export namespace BasicAuthProvider {
    export const AUTH_SCHEME = "KeyAndSecret" as const;
    export const AUTH_CONFIG_ERROR_MESSAGE: string =
        "Please provide username and password when initializing the client" as const;
    export const AUTH_CONFIG_ERROR_MESSAGE_USERNAME: string =
        `Please provide '${USERNAME_PARAM}' when initializing the client, or set the '${ENV_USERNAME}' environment variable` as const;
    export const AUTH_CONFIG_ERROR_MESSAGE_PASSWORD: string =
        `Please provide '${PASSWORD_PARAM}' when initializing the client, or set the '${ENV_PASSWORD}' environment variable` as const;
    export type Options = AuthOptions;
    export type AuthOptions = {
        [USERNAME_PARAM]?: core.Supplier<string> | undefined;
        [PASSWORD_PARAM]?: core.Supplier<string> | undefined;
    };

    export function createInstance(options: Options): core.AuthProvider {
        return new BasicAuthProvider(options);
    }
}
