// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Trading212 from "../../../index.js";

export declare namespace PiesClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class PiesClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<PiesClient.Options>;

    constructor(options: PiesClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * @deprecated
     *
     * Fetches all pies for the account
     *
     * **Rate limit:** 1 req / 30s
     *
     * @param {PiesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Trading212.UnauthorizedError}
     * @throws {@link Trading212.ForbiddenError}
     * @throws {@link Trading212.RequestTimeoutError}
     * @throws {@link Trading212.TooManyRequestsError}
     * @throws {@link errors.Trading212Error}
     * @throws {@link errors.Trading212TimeoutError}
     *
     * @example
     *     await client.pies.list()
     */
    public list(
        requestOptions?: PiesClient.RequestOptions,
    ): core.HttpResponsePromise<Trading212.AccountBucketResultResponse[]> {
        return core.HttpResponsePromise.fromPromise(this.__list(requestOptions));
    }

    private async __list(
        requestOptions?: PiesClient.RequestOptions,
    ): Promise<core.WithRawResponse<Trading212.AccountBucketResultResponse[]>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.Trading212Environment.Demo,
                "api/v0/equity/pies",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Trading212.AccountBucketResultResponse[],
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Trading212.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Trading212.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 408:
                    throw new Trading212.RequestTimeoutError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new Trading212.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.Trading212Error({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api/v0/equity/pies");
    }

    /**
     * @deprecated
     *
     * Creates a pie for the account by given params
     *
     * **Rate limit:** 1 req / 5s
     *
     * @param {Trading212.PieRequest} request
     * @param {PiesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Trading212.BadRequestError}
     * @throws {@link Trading212.UnauthorizedError}
     * @throws {@link Trading212.ForbiddenError}
     * @throws {@link Trading212.RequestTimeoutError}
     * @throws {@link Trading212.TooManyRequestsError}
     * @throws {@link errors.Trading212Error}
     * @throws {@link errors.Trading212TimeoutError}
     *
     * @example
     *     await client.pies.create({})
     */
    public create(
        request: Trading212.PieRequest,
        requestOptions?: PiesClient.RequestOptions,
    ): core.HttpResponsePromise<Trading212.AccountBucketInstrumentsDetailedResponse> {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }

    private async __create(
        request: Trading212.PieRequest,
        requestOptions?: PiesClient.RequestOptions,
    ): Promise<core.WithRawResponse<Trading212.AccountBucketInstrumentsDetailedResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.Trading212Environment.Demo,
                "api/v0/equity/pies",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: 0,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Trading212.AccountBucketInstrumentsDetailedResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Trading212.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Trading212.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Trading212.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 408:
                    throw new Trading212.RequestTimeoutError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new Trading212.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.Trading212Error({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/api/v0/equity/pies");
    }

    /**
     * @deprecated
     *
     * Fetches a pies for the account with detailed information
     *
     * **Rate limit:** 1 req / 5s
     *
     * @param {Trading212.GetPiesRequest} request
     * @param {PiesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Trading212.UnauthorizedError}
     * @throws {@link Trading212.ForbiddenError}
     * @throws {@link Trading212.RequestTimeoutError}
     * @throws {@link Trading212.TooManyRequestsError}
     * @throws {@link errors.Trading212Error}
     * @throws {@link errors.Trading212TimeoutError}
     *
     * @example
     *     await client.pies.get({
     *         id: 1000000
     *     })
     */
    public get(
        request: Trading212.GetPiesRequest,
        requestOptions?: PiesClient.RequestOptions,
    ): core.HttpResponsePromise<Trading212.AccountBucketInstrumentsDetailedResponse> {
        return core.HttpResponsePromise.fromPromise(this.__get(request, requestOptions));
    }

    private async __get(
        request: Trading212.GetPiesRequest,
        requestOptions?: PiesClient.RequestOptions,
    ): Promise<core.WithRawResponse<Trading212.AccountBucketInstrumentsDetailedResponse>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.Trading212Environment.Demo,
                `api/v0/equity/pies/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Trading212.AccountBucketInstrumentsDetailedResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Trading212.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Trading212.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 408:
                    throw new Trading212.RequestTimeoutError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new Trading212.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.Trading212Error({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api/v0/equity/pies/{id}");
    }

    /**
     * @deprecated
     *
     * Updates a pie for the account by given params
     *
     * **Rate limit:** 1 req / 5s
     *
     * @param {Trading212.UpdatePiesRequest} request
     * @param {PiesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Trading212.BadRequestError}
     * @throws {@link Trading212.UnauthorizedError}
     * @throws {@link Trading212.ForbiddenError}
     * @throws {@link Trading212.RequestTimeoutError}
     * @throws {@link Trading212.TooManyRequestsError}
     * @throws {@link errors.Trading212Error}
     * @throws {@link errors.Trading212TimeoutError}
     *
     * @example
     *     await client.pies.update({
     *         id: 1000000,
     *         body: {}
     *     })
     */
    public update(
        request: Trading212.UpdatePiesRequest,
        requestOptions?: PiesClient.RequestOptions,
    ): core.HttpResponsePromise<Trading212.AccountBucketInstrumentsDetailedResponse> {
        return core.HttpResponsePromise.fromPromise(this.__update(request, requestOptions));
    }

    private async __update(
        request: Trading212.UpdatePiesRequest,
        requestOptions?: PiesClient.RequestOptions,
    ): Promise<core.WithRawResponse<Trading212.AccountBucketInstrumentsDetailedResponse>> {
        const { id, body: _body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.Trading212Environment.Demo,
                `api/v0/equity/pies/${core.url.encodePathParam(id)}`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: 0,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Trading212.AccountBucketInstrumentsDetailedResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Trading212.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Trading212.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Trading212.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 408:
                    throw new Trading212.RequestTimeoutError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new Trading212.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.Trading212Error({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/api/v0/equity/pies/{id}");
    }

    /**
     * @deprecated
     *
     * Deletes a pie by given id
     *
     * **Rate limit:** 1 req / 5s
     *
     * @param {Trading212.DeletePiesRequest} request
     * @param {PiesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Trading212.UnauthorizedError}
     * @throws {@link Trading212.ForbiddenError}
     * @throws {@link Trading212.NotFoundError}
     * @throws {@link Trading212.RequestTimeoutError}
     * @throws {@link Trading212.TooManyRequestsError}
     * @throws {@link errors.Trading212Error}
     * @throws {@link errors.Trading212TimeoutError}
     *
     * @example
     *     await client.pies.delete({
     *         id: 1000000
     *     })
     */
    public delete(
        request: Trading212.DeletePiesRequest,
        requestOptions?: PiesClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__delete(request, requestOptions));
    }

    private async __delete(
        request: Trading212.DeletePiesRequest,
        requestOptions?: PiesClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.Trading212Environment.Demo,
                `api/v0/equity/pies/${core.url.encodePathParam(id)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Trading212.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Trading212.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new Trading212.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 408:
                    throw new Trading212.RequestTimeoutError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new Trading212.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.Trading212Error({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/api/v0/equity/pies/{id}");
    }

    /**
     * @deprecated
     *
     * Duplicates a pie for the account
     *
     * **Rate limit:** 1 req / 5s
     *
     * @param {Trading212.DuplicateBucketRequest} request
     * @param {PiesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Trading212.BadRequestError}
     * @throws {@link Trading212.UnauthorizedError}
     * @throws {@link Trading212.ForbiddenError}
     * @throws {@link Trading212.RequestTimeoutError}
     * @throws {@link Trading212.TooManyRequestsError}
     * @throws {@link errors.Trading212Error}
     * @throws {@link errors.Trading212TimeoutError}
     *
     * @example
     *     await client.pies.duplicate({
     *         id: 1000000
     *     })
     */
    public duplicate(
        request: Trading212.DuplicateBucketRequest,
        requestOptions?: PiesClient.RequestOptions,
    ): core.HttpResponsePromise<Trading212.AccountBucketInstrumentsDetailedResponse> {
        return core.HttpResponsePromise.fromPromise(this.__duplicate(request, requestOptions));
    }

    private async __duplicate(
        request: Trading212.DuplicateBucketRequest,
        requestOptions?: PiesClient.RequestOptions,
    ): Promise<core.WithRawResponse<Trading212.AccountBucketInstrumentsDetailedResponse>> {
        const { id, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.Trading212Environment.Demo,
                `api/v0/equity/pies/${core.url.encodePathParam(id)}/duplicate`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: 0,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Trading212.AccountBucketInstrumentsDetailedResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Trading212.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Trading212.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Trading212.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 408:
                    throw new Trading212.RequestTimeoutError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new Trading212.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.Trading212Error({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/v0/equity/pies/{id}/duplicate",
        );
    }
}
