// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: 1000000
 *     }
 */
export interface GetOrdersRequest {
    /** The unique identifier of the order you want to retrieve. */
    id: number;
}
