// This file was auto-generated by Fern from our API Definition.

import type * as Trading212 from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface StopRequest {
    quantity?: number;
    stopPrice?: number;
    ticker?: string;
    /** Expiration */
    timeValidity?: Trading212.TimeValidity;
}
