"""Generate docs/naming-map.md from the upstream spec + fern/overrides.yml.

Run with --check to fail if the committed file is out of date.
"""

from __future__ import annotations

import sys

from overrides import ROOT, operations, snake_case

OUT = ROOT / "docs" / "naming-map.md"


def camel_case(name: str) -> str:
    return name[0].lower() + name[1:]


def render() -> str:
    rows = []
    for op in sorted(operations(), key=lambda o: (o.group or "", o.sdk_method or "")):
        notes = []
        if op.deprecated:
            notes.append("deprecated")
        if op.paginated:
            notes.append("paginated¹")
        rows.append(
            f"| `{op.method.upper()} {op.path.removeprefix('/api/v0/equity')}` "
            f"| `{op.operation_id}` "
            f"| `client.{op.group}.{camel_case(op.sdk_method or '?')}()` "
            f"| `client.{op.group}.{snake_case(op.sdk_method or '?')}()` "
            f"| {', '.join(notes)} |"
        )
    return "\n".join(
        [
            "# SDK naming map",
            "",
            "<!-- Generated by scripts/naming_map.py from fern/overrides.yml. Do not edit by hand. -->",
            "",
            "How each Trading 212 API operation maps to an SDK method. Upstream `operationId`s are",
            "inconsistent (`orders_1`, `placeStopOrder_1` for stop-limit, `getAll`), so every operation is",
            "renamed in `fern/overrides.yml`. Fern then applies each language's casing convention.",
            "",
            "All paths are relative to `/api/v0/equity`.",
            "",
            "| Endpoint | Upstream operationId | TypeScript | Python | Notes |",
            "| --- | --- | --- | --- | --- |",
            *rows,
            "",
            "¹ TypeScript methods return an async-iterable `Page` that fetches further pages automatically",
            "(`for await (const item of await client.history.listOrders())`). In Python, wrap the method with",
            "`t212.pagination.paginate` (`for item in paginate(client.history.list_orders)`).",
            "",
        ]
    )


def main() -> None:
    content = render()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != content:
            sys.exit("docs/naming-map.md is out of date; run python3 scripts/naming_map.py")
        return
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(content)


if __name__ == "__main__":
    main()
