// This file was auto-generated by Fern from our API Definition.

import { hasNextPage, resolveNextPageUrl } from "../../../../nextPage.js";
import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Trading212 from "../../../index.js";

export declare namespace HistoryClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class HistoryClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<HistoryClient.Options>;

    constructor(options: HistoryClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     *
     *
     * **Rate limit:** 6 req / 1m0s
     *
     * @param {Trading212.ListDividendsHistoryRequest} request
     * @param {HistoryClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Trading212.BadRequestError}
     * @throws {@link Trading212.UnauthorizedError}
     * @throws {@link Trading212.ForbiddenError}
     * @throws {@link Trading212.RequestTimeoutError}
     * @throws {@link Trading212.TooManyRequestsError}
     * @throws {@link errors.Trading212Error}
     * @throws {@link errors.Trading212TimeoutError}
     *
     * @example
     *     await client.history.listDividends()
     */
    public async listDividends(
        request: Trading212.ListDividendsHistoryRequest = {},
        requestOptions?: HistoryClient.RequestOptions,
    ): Promise<core.Page<Trading212.HistoryDividendItem, Trading212.PaginatedResponseHistoryDividendItem>> {
        const list = core.HttpResponsePromise.interceptFunction(
            async (
                _requestUrl: string,
            ): Promise<core.WithRawResponse<Trading212.PaginatedResponseHistoryDividendItem>> => {
                const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
                const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
                    _authRequest.headers,
                    this._options?.headers,
                    requestOptions?.headers,
                );
                const _response = await core.fetcher({
                    url: _requestUrl,
                    method: "GET",
                    headers: _headers,
                    timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
                    maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                    fetchFn: this._options?.fetch,
                    logging: this._options.logging,
                });
                if (_response.ok) {
                    return {
                        data: _response.body as Trading212.PaginatedResponseHistoryDividendItem,
                        rawResponse: _response.rawResponse,
                    };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 400:
                            throw new Trading212.BadRequestError(
                                _response.error.body as unknown,
                                _response.rawResponse,
                            );
                        case 401:
                            throw new Trading212.UnauthorizedError(
                                _response.error.body as unknown,
                                _response.rawResponse,
                            );
                        case 403:
                            throw new Trading212.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                        case 408:
                            throw new Trading212.RequestTimeoutError(
                                _response.error.body as unknown,
                                _response.rawResponse,
                            );
                        case 429:
                            throw new Trading212.TooManyRequestsError(
                                _response.error.body as unknown,
                                _response.rawResponse,
                            );
                        default:
                            throw new errors.Trading212Error({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                                rawResponse: _response.rawResponse,
                            });
                    }
                }
                return handleNonStatusCodeError(
                    _response.error,
                    _response.rawResponse,
                    "GET",
                    "/api/v0/equity/history/dividends",
                );
            },
        );
        const _baseUrl =
            (await core.Supplier.get(this._options.baseUrl)) ??
            (await core.Supplier.get(this._options.environment)) ??
            environments.Trading212Environment.Demo;
        const initialRequest = core.HttpResponsePromise.interceptFunction(
            async (): Promise<core.WithRawResponse<Trading212.PaginatedResponseHistoryDividendItem>> => {
                const { cursor, ticker, limit } = request;
                const _queryParams: Record<string, unknown> = {
                    cursor,
                    ticker,
                    limit,
                };
                const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
                const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
                    _authRequest.headers,
                    this._options?.headers,
                    requestOptions?.headers,
                );
                const _response = await core.fetcher({
                    url: core.url.join(_baseUrl, "api/v0/equity/history/dividends"),
                    method: "GET",
                    headers: _headers,
                    queryString: core.url
                        .queryBuilder()
                        .addMany(_queryParams)
                        .mergeAdditional(requestOptions?.queryParams)
                        .build(),
                    timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
                    maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                    fetchFn: this._options?.fetch,
                    logging: this._options.logging,
                });
                if (_response.ok) {
                    return {
                        data: _response.body as Trading212.PaginatedResponseHistoryDividendItem,
                        rawResponse: _response.rawResponse,
                    };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 400:
                            throw new Trading212.BadRequestError(
                                _response.error.body as unknown,
                                _response.rawResponse,
                            );
                        case 401:
                            throw new Trading212.UnauthorizedError(
                                _response.error.body as unknown,
                                _response.rawResponse,
                            );
                        case 403:
                            throw new Trading212.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                        case 408:
                            throw new Trading212.RequestTimeoutError(
                                _response.error.body as unknown,
                                _response.rawResponse,
                            );
                        case 429:
                            throw new Trading212.TooManyRequestsError(
                                _response.error.body as unknown,
                                _response.rawResponse,
                            );
                        default:
                            throw new errors.Trading212Error({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                                rawResponse: _response.rawResponse,
                            });
                    }
                }
                return handleNonStatusCodeError(
                    _response.error,
                    _response.rawResponse,
                    "GET",
                    "/api/v0/equity/history/dividends",
                );
            },
        );
        const dataWithRawResponse = await initialRequest().withRawResponse();
        return new core.Page<Trading212.HistoryDividendItem, Trading212.PaginatedResponseHistoryDividendItem>({
            response: dataWithRawResponse.data,
            rawResponse: dataWithRawResponse.rawResponse,
            hasNextPage: (response) => hasNextPage(response?.nextPagePath),
            getItems: (response) => response?.items ?? [],
            loadPage: (response) => {
                return list(resolveNextPageUrl(_baseUrl, response!.nextPagePath!, "/api/v0/equity/history/dividends"));
            },
        });
    }

    /**
     * Retrieves a list of all requested CSV reports and their current status.
     *
     *
     * **Asynchronous Workflow:**
     *
     * 1. Call `POST /history/exports` to request a report. You will receive a
     * `reportId`.
     *
     * 2. Periodically call this endpoint (`GET /history/exports`) to check the
     * `status` of the report corresponding to your `reportId`.
     *
     * 3. Once the status is `Finished`, the `downloadLink` field will contain
     * a URL to download the CSV file.
     *
     * **Rate limit:** 1 req / 1m0s
     *
     * @param {HistoryClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Trading212.BadRequestError}
     * @throws {@link Trading212.UnauthorizedError}
     * @throws {@link Trading212.ForbiddenError}
     * @throws {@link Trading212.RequestTimeoutError}
     * @throws {@link Trading212.TooManyRequestsError}
     * @throws {@link errors.Trading212Error}
     * @throws {@link errors.Trading212TimeoutError}
     *
     * @example
     *     await client.history.listReports()
     */
    public listReports(
        requestOptions?: HistoryClient.RequestOptions,
    ): core.HttpResponsePromise<Trading212.ReportResponse[]> {
        return core.HttpResponsePromise.fromPromise(this.__listReports(requestOptions));
    }

    private async __listReports(
        requestOptions?: HistoryClient.RequestOptions,
    ): Promise<core.WithRawResponse<Trading212.ReportResponse[]>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.Trading212Environment.Demo,
                "api/v0/equity/history/exports",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Trading212.ReportResponse[], rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Trading212.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Trading212.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Trading212.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 408:
                    throw new Trading212.RequestTimeoutError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new Trading212.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.Trading212Error({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v0/equity/history/exports",
        );
    }

    /**
     * Initiates the generation of a CSV report containing historical account
     * data. This is an asynchronous operation. The response will include a
     * `reportId` which you can use to track the status of the generation
     * process using the `GET /history/exports` endpoint.
     *
     * **Rate limit:** 1 req / 30s
     *
     * @param {Trading212.PublicReportRequest} request
     * @param {HistoryClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Trading212.BadRequestError}
     * @throws {@link Trading212.UnauthorizedError}
     * @throws {@link Trading212.ForbiddenError}
     * @throws {@link Trading212.RequestTimeoutError}
     * @throws {@link Trading212.TooManyRequestsError}
     * @throws {@link errors.Trading212Error}
     * @throws {@link errors.Trading212TimeoutError}
     *
     * @example
     *     await client.history.requestReport()
     */
    public requestReport(
        request: Trading212.PublicReportRequest = {},
        requestOptions?: HistoryClient.RequestOptions,
    ): core.HttpResponsePromise<Trading212.EnqueuedReportResponse> {
        return core.HttpResponsePromise.fromPromise(this.__requestReport(request, requestOptions));
    }

    private async __requestReport(
        request: Trading212.PublicReportRequest = {},
        requestOptions?: HistoryClient.RequestOptions,
    ): Promise<core.WithRawResponse<Trading212.EnqueuedReportResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.Trading212Environment.Demo,
                "api/v0/equity/history/exports",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: 0,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Trading212.EnqueuedReportResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Trading212.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Trading212.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Trading212.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 408:
                    throw new Trading212.RequestTimeoutError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new Trading212.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.Trading212Error({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/v0/equity/history/exports",
        );
    }

    /**
     *
     *
     * **Rate limit:** 6 req / 1m0s
     *
     * @param {Trading212.ListOrdersHistoryRequest} request
     * @param {HistoryClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Trading212.BadRequestError}
     * @throws {@link Trading212.UnauthorizedError}
     * @throws {@link Trading212.ForbiddenError}
     * @throws {@link Trading212.RequestTimeoutError}
     * @throws {@link Trading212.TooManyRequestsError}
     * @throws {@link errors.Trading212Error}
     * @throws {@link errors.Trading212TimeoutError}
     *
     * @example
     *     await client.history.listOrders()
     */
    public async listOrders(
        request: Trading212.ListOrdersHistoryRequest = {},
        requestOptions?: HistoryClient.RequestOptions,
    ): Promise<core.Page<Trading212.HistoricalOrder, Trading212.PaginatedResponseHistoricalOrder>> {
        const list = core.HttpResponsePromise.interceptFunction(
            async (_requestUrl: string): Promise<core.WithRawResponse<Trading212.PaginatedResponseHistoricalOrder>> => {
                const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
                const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
                    _authRequest.headers,
                    this._options?.headers,
                    requestOptions?.headers,
                );
                const _response = await core.fetcher({
                    url: _requestUrl,
                    method: "GET",
                    headers: _headers,
                    timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
                    maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                    fetchFn: this._options?.fetch,
                    logging: this._options.logging,
                });
                if (_response.ok) {
                    return {
                        data: _response.body as Trading212.PaginatedResponseHistoricalOrder,
                        rawResponse: _response.rawResponse,
                    };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 400:
                            throw new Trading212.BadRequestError(
                                _response.error.body as unknown,
                                _response.rawResponse,
                            );
                        case 401:
                            throw new Trading212.UnauthorizedError(
                                _response.error.body as unknown,
                                _response.rawResponse,
                            );
                        case 403:
                            throw new Trading212.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                        case 408:
                            throw new Trading212.RequestTimeoutError(
                                _response.error.body as unknown,
                                _response.rawResponse,
                            );
                        case 429:
                            throw new Trading212.TooManyRequestsError(
                                _response.error.body as unknown,
                                _response.rawResponse,
                            );
                        default:
                            throw new errors.Trading212Error({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                                rawResponse: _response.rawResponse,
                            });
                    }
                }
                return handleNonStatusCodeError(
                    _response.error,
                    _response.rawResponse,
                    "GET",
                    "/api/v0/equity/history/orders",
                );
            },
        );
        const _baseUrl =
            (await core.Supplier.get(this._options.baseUrl)) ??
            (await core.Supplier.get(this._options.environment)) ??
            environments.Trading212Environment.Demo;
        const initialRequest = core.HttpResponsePromise.interceptFunction(
            async (): Promise<core.WithRawResponse<Trading212.PaginatedResponseHistoricalOrder>> => {
                const { cursor, ticker, limit } = request;
                const _queryParams: Record<string, unknown> = {
                    cursor,
                    ticker,
                    limit,
                };
                const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
                const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
                    _authRequest.headers,
                    this._options?.headers,
                    requestOptions?.headers,
                );
                const _response = await core.fetcher({
                    url: core.url.join(_baseUrl, "api/v0/equity/history/orders"),
                    method: "GET",
                    headers: _headers,
                    queryString: core.url
                        .queryBuilder()
                        .addMany(_queryParams)
                        .mergeAdditional(requestOptions?.queryParams)
                        .build(),
                    timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
                    maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                    fetchFn: this._options?.fetch,
                    logging: this._options.logging,
                });
                if (_response.ok) {
                    return {
                        data: _response.body as Trading212.PaginatedResponseHistoricalOrder,
                        rawResponse: _response.rawResponse,
                    };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 400:
                            throw new Trading212.BadRequestError(
                                _response.error.body as unknown,
                                _response.rawResponse,
                            );
                        case 401:
                            throw new Trading212.UnauthorizedError(
                                _response.error.body as unknown,
                                _response.rawResponse,
                            );
                        case 403:
                            throw new Trading212.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                        case 408:
                            throw new Trading212.RequestTimeoutError(
                                _response.error.body as unknown,
                                _response.rawResponse,
                            );
                        case 429:
                            throw new Trading212.TooManyRequestsError(
                                _response.error.body as unknown,
                                _response.rawResponse,
                            );
                        default:
                            throw new errors.Trading212Error({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                                rawResponse: _response.rawResponse,
                            });
                    }
                }
                return handleNonStatusCodeError(
                    _response.error,
                    _response.rawResponse,
                    "GET",
                    "/api/v0/equity/history/orders",
                );
            },
        );
        const dataWithRawResponse = await initialRequest().withRawResponse();
        return new core.Page<Trading212.HistoricalOrder, Trading212.PaginatedResponseHistoricalOrder>({
            response: dataWithRawResponse.data,
            rawResponse: dataWithRawResponse.rawResponse,
            hasNextPage: (response) => hasNextPage(response?.nextPagePath),
            getItems: (response) => response?.items ?? [],
            loadPage: (response) => {
                return list(resolveNextPageUrl(_baseUrl, response!.nextPagePath!, "/api/v0/equity/history/orders"));
            },
        });
    }

    /**
     * Fetch superficial information about movements to and from your account
     *
     * **Rate limit:** 6 req / 1m0s
     *
     * @param {Trading212.ListTransactionsHistoryRequest} request
     * @param {HistoryClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Trading212.BadRequestError}
     * @throws {@link Trading212.UnauthorizedError}
     * @throws {@link Trading212.ForbiddenError}
     * @throws {@link Trading212.RequestTimeoutError}
     * @throws {@link Trading212.TooManyRequestsError}
     * @throws {@link errors.Trading212Error}
     * @throws {@link errors.Trading212TimeoutError}
     *
     * @example
     *     await client.history.listTransactions()
     */
    public async listTransactions(
        request: Trading212.ListTransactionsHistoryRequest = {},
        requestOptions?: HistoryClient.RequestOptions,
    ): Promise<core.Page<Trading212.HistoryTransactionItem, Trading212.PaginatedResponseHistoryTransactionItem>> {
        const list = core.HttpResponsePromise.interceptFunction(
            async (
                _requestUrl: string,
            ): Promise<core.WithRawResponse<Trading212.PaginatedResponseHistoryTransactionItem>> => {
                const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
                const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
                    _authRequest.headers,
                    this._options?.headers,
                    requestOptions?.headers,
                );
                const _response = await core.fetcher({
                    url: _requestUrl,
                    method: "GET",
                    headers: _headers,
                    timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
                    maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                    fetchFn: this._options?.fetch,
                    logging: this._options.logging,
                });
                if (_response.ok) {
                    return {
                        data: _response.body as Trading212.PaginatedResponseHistoryTransactionItem,
                        rawResponse: _response.rawResponse,
                    };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 400:
                            throw new Trading212.BadRequestError(
                                _response.error.body as unknown,
                                _response.rawResponse,
                            );
                        case 401:
                            throw new Trading212.UnauthorizedError(
                                _response.error.body as unknown,
                                _response.rawResponse,
                            );
                        case 403:
                            throw new Trading212.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                        case 408:
                            throw new Trading212.RequestTimeoutError(
                                _response.error.body as unknown,
                                _response.rawResponse,
                            );
                        case 429:
                            throw new Trading212.TooManyRequestsError(
                                _response.error.body as unknown,
                                _response.rawResponse,
                            );
                        default:
                            throw new errors.Trading212Error({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                                rawResponse: _response.rawResponse,
                            });
                    }
                }
                return handleNonStatusCodeError(
                    _response.error,
                    _response.rawResponse,
                    "GET",
                    "/api/v0/equity/history/transactions",
                );
            },
        );
        const _baseUrl =
            (await core.Supplier.get(this._options.baseUrl)) ??
            (await core.Supplier.get(this._options.environment)) ??
            environments.Trading212Environment.Demo;
        const initialRequest = core.HttpResponsePromise.interceptFunction(
            async (): Promise<core.WithRawResponse<Trading212.PaginatedResponseHistoryTransactionItem>> => {
                const { cursor, time, limit } = request;
                const _queryParams: Record<string, unknown> = {
                    cursor,
                    time: time != null ? time : undefined,
                    limit,
                };
                const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
                const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
                    _authRequest.headers,
                    this._options?.headers,
                    requestOptions?.headers,
                );
                const _response = await core.fetcher({
                    url: core.url.join(_baseUrl, "api/v0/equity/history/transactions"),
                    method: "GET",
                    headers: _headers,
                    queryString: core.url
                        .queryBuilder()
                        .addMany(_queryParams)
                        .mergeAdditional(requestOptions?.queryParams)
                        .build(),
                    timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
                    maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                    fetchFn: this._options?.fetch,
                    logging: this._options.logging,
                });
                if (_response.ok) {
                    return {
                        data: _response.body as Trading212.PaginatedResponseHistoryTransactionItem,
                        rawResponse: _response.rawResponse,
                    };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 400:
                            throw new Trading212.BadRequestError(
                                _response.error.body as unknown,
                                _response.rawResponse,
                            );
                        case 401:
                            throw new Trading212.UnauthorizedError(
                                _response.error.body as unknown,
                                _response.rawResponse,
                            );
                        case 403:
                            throw new Trading212.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                        case 408:
                            throw new Trading212.RequestTimeoutError(
                                _response.error.body as unknown,
                                _response.rawResponse,
                            );
                        case 429:
                            throw new Trading212.TooManyRequestsError(
                                _response.error.body as unknown,
                                _response.rawResponse,
                            );
                        default:
                            throw new errors.Trading212Error({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                                rawResponse: _response.rawResponse,
                            });
                    }
                }
                return handleNonStatusCodeError(
                    _response.error,
                    _response.rawResponse,
                    "GET",
                    "/api/v0/equity/history/transactions",
                );
            },
        );
        const dataWithRawResponse = await initialRequest().withRawResponse();
        return new core.Page<Trading212.HistoryTransactionItem, Trading212.PaginatedResponseHistoryTransactionItem>({
            response: dataWithRawResponse.data,
            rawResponse: dataWithRawResponse.rawResponse,
            hasNextPage: (response) => hasNextPage(response?.nextPagePath),
            getItems: (response) => response?.items ?? [],
            loadPage: (response) => {
                return list(resolveNextPageUrl(_baseUrl, response!.nextPagePath!, "/api/v0/equity/history/transactions"));
            },
        });
    }
}
